// Code generated by ent, DO NOT EDIT.

package ent

import (
	"authorization-go-echo/ent/appclient"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AppClientCreate is the builder for creating a AppClient entity.
type AppClientCreate struct {
	config
	mutation *AppClientMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *AppClientCreate) SetName(v string) *AppClientCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetIdentifier sets the "identifier" field.
func (_c *AppClientCreate) SetIdentifier(v string) *AppClientCreate {
	_c.mutation.SetIdentifier(v)
	return _c
}

// SetPostCode sets the "post_code" field.
func (_c *AppClientCreate) SetPostCode(v string) *AppClientCreate {
	_c.mutation.SetPostCode(v)
	return _c
}

// SetNillablePostCode sets the "post_code" field if the given value is not nil.
func (_c *AppClientCreate) SetNillablePostCode(v *string) *AppClientCreate {
	if v != nil {
		_c.SetPostCode(*v)
	}
	return _c
}

// SetPref sets the "pref" field.
func (_c *AppClientCreate) SetPref(v string) *AppClientCreate {
	_c.mutation.SetPref(v)
	return _c
}

// SetNillablePref sets the "pref" field if the given value is not nil.
func (_c *AppClientCreate) SetNillablePref(v *string) *AppClientCreate {
	if v != nil {
		_c.SetPref(*v)
	}
	return _c
}

// SetCity sets the "city" field.
func (_c *AppClientCreate) SetCity(v string) *AppClientCreate {
	_c.mutation.SetCity(v)
	return _c
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_c *AppClientCreate) SetNillableCity(v *string) *AppClientCreate {
	if v != nil {
		_c.SetCity(*v)
	}
	return _c
}

// SetAddress sets the "address" field.
func (_c *AppClientCreate) SetAddress(v string) *AppClientCreate {
	_c.mutation.SetAddress(v)
	return _c
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_c *AppClientCreate) SetNillableAddress(v *string) *AppClientCreate {
	if v != nil {
		_c.SetAddress(*v)
	}
	return _c
}

// SetBuilding sets the "building" field.
func (_c *AppClientCreate) SetBuilding(v string) *AppClientCreate {
	_c.mutation.SetBuilding(v)
	return _c
}

// SetNillableBuilding sets the "building" field if the given value is not nil.
func (_c *AppClientCreate) SetNillableBuilding(v *string) *AppClientCreate {
	if v != nil {
		_c.SetBuilding(*v)
	}
	return _c
}

// SetTel sets the "tel" field.
func (_c *AppClientCreate) SetTel(v string) *AppClientCreate {
	_c.mutation.SetTel(v)
	return _c
}

// SetNillableTel sets the "tel" field if the given value is not nil.
func (_c *AppClientCreate) SetNillableTel(v *string) *AppClientCreate {
	if v != nil {
		_c.SetTel(*v)
	}
	return _c
}

// SetEmail sets the "email" field.
func (_c *AppClientCreate) SetEmail(v string) *AppClientCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_c *AppClientCreate) SetNillableEmail(v *string) *AppClientCreate {
	if v != nil {
		_c.SetEmail(*v)
	}
	return _c
}

// SetAccessToken sets the "access_token" field.
func (_c *AppClientCreate) SetAccessToken(v string) *AppClientCreate {
	_c.mutation.SetAccessToken(v)
	return _c
}

// SetPrivateKey sets the "private_key" field.
func (_c *AppClientCreate) SetPrivateKey(v string) *AppClientCreate {
	_c.mutation.SetPrivateKey(v)
	return _c
}

// SetPublicKey sets the "public_key" field.
func (_c *AppClientCreate) SetPublicKey(v string) *AppClientCreate {
	_c.mutation.SetPublicKey(v)
	return _c
}

// SetFingerprint sets the "fingerprint" field.
func (_c *AppClientCreate) SetFingerprint(v string) *AppClientCreate {
	_c.mutation.SetFingerprint(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *AppClientCreate) SetStatus(v int) *AppClientCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AppClientCreate) SetNillableStatus(v *int) *AppClientCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetStartAt sets the "start_at" field.
func (_c *AppClientCreate) SetStartAt(v time.Time) *AppClientCreate {
	_c.mutation.SetStartAt(v)
	return _c
}

// SetNillableStartAt sets the "start_at" field if the given value is not nil.
func (_c *AppClientCreate) SetNillableStartAt(v *time.Time) *AppClientCreate {
	if v != nil {
		_c.SetStartAt(*v)
	}
	return _c
}

// SetStopAt sets the "stop_at" field.
func (_c *AppClientCreate) SetStopAt(v time.Time) *AppClientCreate {
	_c.mutation.SetStopAt(v)
	return _c
}

// SetNillableStopAt sets the "stop_at" field if the given value is not nil.
func (_c *AppClientCreate) SetNillableStopAt(v *time.Time) *AppClientCreate {
	if v != nil {
		_c.SetStopAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AppClientCreate) SetCreatedAt(v time.Time) *AppClientCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AppClientCreate) SetNillableCreatedAt(v *time.Time) *AppClientCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *AppClientCreate) SetCreatedBy(v uint) *AppClientCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *AppClientCreate) SetNillableCreatedBy(v *uint) *AppClientCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AppClientCreate) SetUpdatedAt(v time.Time) *AppClientCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AppClientCreate) SetNillableUpdatedAt(v *time.Time) *AppClientCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *AppClientCreate) SetUpdatedBy(v uint) *AppClientCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *AppClientCreate) SetNillableUpdatedBy(v *uint) *AppClientCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *AppClientCreate) SetDeletedAt(v time.Time) *AppClientCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *AppClientCreate) SetNillableDeletedAt(v *time.Time) *AppClientCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *AppClientCreate) SetDeletedBy(v uint) *AppClientCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *AppClientCreate) SetNillableDeletedBy(v *uint) *AppClientCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *AppClientCreate) SetVersion(v int) *AppClientCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *AppClientCreate) SetNillableVersion(v *int) *AppClientCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AppClientCreate) SetID(v uint64) *AppClientCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AppClientMutation object of the builder.
func (_c *AppClientCreate) Mutation() *AppClientMutation {
	return _c.mutation
}

// Save creates the AppClient in the database.
func (_c *AppClientCreate) Save(ctx context.Context) (*AppClient, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AppClientCreate) SaveX(ctx context.Context) *AppClient {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AppClientCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AppClientCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AppClientCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := appclient.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := appclient.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := appclient.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := appclient.DefaultVersion
		_c.mutation.SetVersion(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AppClientCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "AppClient.name"`)}
	}
	if _, ok := _c.mutation.Identifier(); !ok {
		return &ValidationError{Name: "identifier", err: errors.New(`ent: missing required field "AppClient.identifier"`)}
	}
	if _, ok := _c.mutation.AccessToken(); !ok {
		return &ValidationError{Name: "access_token", err: errors.New(`ent: missing required field "AppClient.access_token"`)}
	}
	if _, ok := _c.mutation.PrivateKey(); !ok {
		return &ValidationError{Name: "private_key", err: errors.New(`ent: missing required field "AppClient.private_key"`)}
	}
	if _, ok := _c.mutation.PublicKey(); !ok {
		return &ValidationError{Name: "public_key", err: errors.New(`ent: missing required field "AppClient.public_key"`)}
	}
	if _, ok := _c.mutation.Fingerprint(); !ok {
		return &ValidationError{Name: "fingerprint", err: errors.New(`ent: missing required field "AppClient.fingerprint"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AppClient.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AppClient.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AppClient.updated_at"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "AppClient.version"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := appclient.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "AppClient.id": %w`, err)}
		}
	}
	return nil
}

func (_c *AppClientCreate) sqlSave(ctx context.Context) (*AppClient, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AppClientCreate) createSpec() (*AppClient, *sqlgraph.CreateSpec) {
	var (
		_node = &AppClient{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(appclient.Table, sqlgraph.NewFieldSpec(appclient.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(appclient.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Identifier(); ok {
		_spec.SetField(appclient.FieldIdentifier, field.TypeString, value)
		_node.Identifier = value
	}
	if value, ok := _c.mutation.PostCode(); ok {
		_spec.SetField(appclient.FieldPostCode, field.TypeString, value)
		_node.PostCode = value
	}
	if value, ok := _c.mutation.Pref(); ok {
		_spec.SetField(appclient.FieldPref, field.TypeString, value)
		_node.Pref = value
	}
	if value, ok := _c.mutation.City(); ok {
		_spec.SetField(appclient.FieldCity, field.TypeString, value)
		_node.City = value
	}
	if value, ok := _c.mutation.Address(); ok {
		_spec.SetField(appclient.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := _c.mutation.Building(); ok {
		_spec.SetField(appclient.FieldBuilding, field.TypeString, value)
		_node.Building = value
	}
	if value, ok := _c.mutation.Tel(); ok {
		_spec.SetField(appclient.FieldTel, field.TypeString, value)
		_node.Tel = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(appclient.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.AccessToken(); ok {
		_spec.SetField(appclient.FieldAccessToken, field.TypeString, value)
		_node.AccessToken = value
	}
	if value, ok := _c.mutation.PrivateKey(); ok {
		_spec.SetField(appclient.FieldPrivateKey, field.TypeString, value)
		_node.PrivateKey = value
	}
	if value, ok := _c.mutation.PublicKey(); ok {
		_spec.SetField(appclient.FieldPublicKey, field.TypeString, value)
		_node.PublicKey = value
	}
	if value, ok := _c.mutation.Fingerprint(); ok {
		_spec.SetField(appclient.FieldFingerprint, field.TypeString, value)
		_node.Fingerprint = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(appclient.FieldStatus, field.TypeInt, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.StartAt(); ok {
		_spec.SetField(appclient.FieldStartAt, field.TypeTime, value)
		_node.StartAt = &value
	}
	if value, ok := _c.mutation.StopAt(); ok {
		_spec.SetField(appclient.FieldStopAt, field.TypeTime, value)
		_node.StopAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(appclient.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(appclient.FieldCreatedBy, field.TypeUint, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(appclient.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(appclient.FieldUpdatedBy, field.TypeUint, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(appclient.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(appclient.FieldDeletedBy, field.TypeUint, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(appclient.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	return _node, _spec
}

// AppClientCreateBulk is the builder for creating many AppClient entities in bulk.
type AppClientCreateBulk struct {
	config
	err      error
	builders []*AppClientCreate
}

// Save creates the AppClient entities in the database.
func (_c *AppClientCreateBulk) Save(ctx context.Context) ([]*AppClient, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AppClient, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AppClientMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AppClientCreateBulk) SaveX(ctx context.Context) []*AppClient {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AppClientCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AppClientCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
