// Code generated by ent, DO NOT EDIT.

package ent

import (
	"authorization-go-echo/ent/appclient"
	"authorization-go-echo/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AppClientUpdate is the builder for updating AppClient entities.
type AppClientUpdate struct {
	config
	hooks    []Hook
	mutation *AppClientMutation
}

// Where appends a list predicates to the AppClientUpdate builder.
func (_u *AppClientUpdate) Where(ps ...predicate.AppClient) *AppClientUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *AppClientUpdate) SetName(v string) *AppClientUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AppClientUpdate) SetNillableName(v *string) *AppClientUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetIdentifier sets the "identifier" field.
func (_u *AppClientUpdate) SetIdentifier(v string) *AppClientUpdate {
	_u.mutation.SetIdentifier(v)
	return _u
}

// SetNillableIdentifier sets the "identifier" field if the given value is not nil.
func (_u *AppClientUpdate) SetNillableIdentifier(v *string) *AppClientUpdate {
	if v != nil {
		_u.SetIdentifier(*v)
	}
	return _u
}

// SetPostCode sets the "post_code" field.
func (_u *AppClientUpdate) SetPostCode(v string) *AppClientUpdate {
	_u.mutation.SetPostCode(v)
	return _u
}

// SetNillablePostCode sets the "post_code" field if the given value is not nil.
func (_u *AppClientUpdate) SetNillablePostCode(v *string) *AppClientUpdate {
	if v != nil {
		_u.SetPostCode(*v)
	}
	return _u
}

// ClearPostCode clears the value of the "post_code" field.
func (_u *AppClientUpdate) ClearPostCode() *AppClientUpdate {
	_u.mutation.ClearPostCode()
	return _u
}

// SetPref sets the "pref" field.
func (_u *AppClientUpdate) SetPref(v string) *AppClientUpdate {
	_u.mutation.SetPref(v)
	return _u
}

// SetNillablePref sets the "pref" field if the given value is not nil.
func (_u *AppClientUpdate) SetNillablePref(v *string) *AppClientUpdate {
	if v != nil {
		_u.SetPref(*v)
	}
	return _u
}

// ClearPref clears the value of the "pref" field.
func (_u *AppClientUpdate) ClearPref() *AppClientUpdate {
	_u.mutation.ClearPref()
	return _u
}

// SetCity sets the "city" field.
func (_u *AppClientUpdate) SetCity(v string) *AppClientUpdate {
	_u.mutation.SetCity(v)
	return _u
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_u *AppClientUpdate) SetNillableCity(v *string) *AppClientUpdate {
	if v != nil {
		_u.SetCity(*v)
	}
	return _u
}

// ClearCity clears the value of the "city" field.
func (_u *AppClientUpdate) ClearCity() *AppClientUpdate {
	_u.mutation.ClearCity()
	return _u
}

// SetAddress sets the "address" field.
func (_u *AppClientUpdate) SetAddress(v string) *AppClientUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *AppClientUpdate) SetNillableAddress(v *string) *AppClientUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// ClearAddress clears the value of the "address" field.
func (_u *AppClientUpdate) ClearAddress() *AppClientUpdate {
	_u.mutation.ClearAddress()
	return _u
}

// SetBuilding sets the "building" field.
func (_u *AppClientUpdate) SetBuilding(v string) *AppClientUpdate {
	_u.mutation.SetBuilding(v)
	return _u
}

// SetNillableBuilding sets the "building" field if the given value is not nil.
func (_u *AppClientUpdate) SetNillableBuilding(v *string) *AppClientUpdate {
	if v != nil {
		_u.SetBuilding(*v)
	}
	return _u
}

// ClearBuilding clears the value of the "building" field.
func (_u *AppClientUpdate) ClearBuilding() *AppClientUpdate {
	_u.mutation.ClearBuilding()
	return _u
}

// SetTel sets the "tel" field.
func (_u *AppClientUpdate) SetTel(v string) *AppClientUpdate {
	_u.mutation.SetTel(v)
	return _u
}

// SetNillableTel sets the "tel" field if the given value is not nil.
func (_u *AppClientUpdate) SetNillableTel(v *string) *AppClientUpdate {
	if v != nil {
		_u.SetTel(*v)
	}
	return _u
}

// ClearTel clears the value of the "tel" field.
func (_u *AppClientUpdate) ClearTel() *AppClientUpdate {
	_u.mutation.ClearTel()
	return _u
}

// SetEmail sets the "email" field.
func (_u *AppClientUpdate) SetEmail(v string) *AppClientUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *AppClientUpdate) SetNillableEmail(v *string) *AppClientUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *AppClientUpdate) ClearEmail() *AppClientUpdate {
	_u.mutation.ClearEmail()
	return _u
}

// SetAccessToken sets the "access_token" field.
func (_u *AppClientUpdate) SetAccessToken(v string) *AppClientUpdate {
	_u.mutation.SetAccessToken(v)
	return _u
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (_u *AppClientUpdate) SetNillableAccessToken(v *string) *AppClientUpdate {
	if v != nil {
		_u.SetAccessToken(*v)
	}
	return _u
}

// SetPrivateKey sets the "private_key" field.
func (_u *AppClientUpdate) SetPrivateKey(v string) *AppClientUpdate {
	_u.mutation.SetPrivateKey(v)
	return _u
}

// SetNillablePrivateKey sets the "private_key" field if the given value is not nil.
func (_u *AppClientUpdate) SetNillablePrivateKey(v *string) *AppClientUpdate {
	if v != nil {
		_u.SetPrivateKey(*v)
	}
	return _u
}

// SetPublicKey sets the "public_key" field.
func (_u *AppClientUpdate) SetPublicKey(v string) *AppClientUpdate {
	_u.mutation.SetPublicKey(v)
	return _u
}

// SetNillablePublicKey sets the "public_key" field if the given value is not nil.
func (_u *AppClientUpdate) SetNillablePublicKey(v *string) *AppClientUpdate {
	if v != nil {
		_u.SetPublicKey(*v)
	}
	return _u
}

// SetFingerprint sets the "fingerprint" field.
func (_u *AppClientUpdate) SetFingerprint(v string) *AppClientUpdate {
	_u.mutation.SetFingerprint(v)
	return _u
}

// SetNillableFingerprint sets the "fingerprint" field if the given value is not nil.
func (_u *AppClientUpdate) SetNillableFingerprint(v *string) *AppClientUpdate {
	if v != nil {
		_u.SetFingerprint(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AppClientUpdate) SetStatus(v int) *AppClientUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AppClientUpdate) SetNillableStatus(v *int) *AppClientUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *AppClientUpdate) AddStatus(v int) *AppClientUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetStartAt sets the "start_at" field.
func (_u *AppClientUpdate) SetStartAt(v time.Time) *AppClientUpdate {
	_u.mutation.SetStartAt(v)
	return _u
}

// SetNillableStartAt sets the "start_at" field if the given value is not nil.
func (_u *AppClientUpdate) SetNillableStartAt(v *time.Time) *AppClientUpdate {
	if v != nil {
		_u.SetStartAt(*v)
	}
	return _u
}

// ClearStartAt clears the value of the "start_at" field.
func (_u *AppClientUpdate) ClearStartAt() *AppClientUpdate {
	_u.mutation.ClearStartAt()
	return _u
}

// SetStopAt sets the "stop_at" field.
func (_u *AppClientUpdate) SetStopAt(v time.Time) *AppClientUpdate {
	_u.mutation.SetStopAt(v)
	return _u
}

// SetNillableStopAt sets the "stop_at" field if the given value is not nil.
func (_u *AppClientUpdate) SetNillableStopAt(v *time.Time) *AppClientUpdate {
	if v != nil {
		_u.SetStopAt(*v)
	}
	return _u
}

// ClearStopAt clears the value of the "stop_at" field.
func (_u *AppClientUpdate) ClearStopAt() *AppClientUpdate {
	_u.mutation.ClearStopAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AppClientUpdate) SetCreatedAt(v time.Time) *AppClientUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AppClientUpdate) SetNillableCreatedAt(v *time.Time) *AppClientUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *AppClientUpdate) SetCreatedBy(v uint) *AppClientUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *AppClientUpdate) SetNillableCreatedBy(v *uint) *AppClientUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *AppClientUpdate) AddCreatedBy(v int) *AppClientUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *AppClientUpdate) ClearCreatedBy() *AppClientUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AppClientUpdate) SetUpdatedAt(v time.Time) *AppClientUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *AppClientUpdate) SetNillableUpdatedAt(v *time.Time) *AppClientUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *AppClientUpdate) SetUpdatedBy(v uint) *AppClientUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *AppClientUpdate) SetNillableUpdatedBy(v *uint) *AppClientUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *AppClientUpdate) AddUpdatedBy(v int) *AppClientUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *AppClientUpdate) ClearUpdatedBy() *AppClientUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AppClientUpdate) SetDeletedAt(v time.Time) *AppClientUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AppClientUpdate) SetNillableDeletedAt(v *time.Time) *AppClientUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AppClientUpdate) ClearDeletedAt() *AppClientUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *AppClientUpdate) SetDeletedBy(v uint) *AppClientUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *AppClientUpdate) SetNillableDeletedBy(v *uint) *AppClientUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *AppClientUpdate) AddDeletedBy(v int) *AppClientUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *AppClientUpdate) ClearDeletedBy() *AppClientUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetVersion sets the "version" field.
func (_u *AppClientUpdate) SetVersion(v int) *AppClientUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *AppClientUpdate) SetNillableVersion(v *int) *AppClientUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *AppClientUpdate) AddVersion(v int) *AppClientUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the AppClientMutation object of the builder.
func (_u *AppClientUpdate) Mutation() *AppClientMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AppClientUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AppClientUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AppClientUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AppClientUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AppClientUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(appclient.Table, appclient.Columns, sqlgraph.NewFieldSpec(appclient.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(appclient.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Identifier(); ok {
		_spec.SetField(appclient.FieldIdentifier, field.TypeString, value)
	}
	if value, ok := _u.mutation.PostCode(); ok {
		_spec.SetField(appclient.FieldPostCode, field.TypeString, value)
	}
	if _u.mutation.PostCodeCleared() {
		_spec.ClearField(appclient.FieldPostCode, field.TypeString)
	}
	if value, ok := _u.mutation.Pref(); ok {
		_spec.SetField(appclient.FieldPref, field.TypeString, value)
	}
	if _u.mutation.PrefCleared() {
		_spec.ClearField(appclient.FieldPref, field.TypeString)
	}
	if value, ok := _u.mutation.City(); ok {
		_spec.SetField(appclient.FieldCity, field.TypeString, value)
	}
	if _u.mutation.CityCleared() {
		_spec.ClearField(appclient.FieldCity, field.TypeString)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(appclient.FieldAddress, field.TypeString, value)
	}
	if _u.mutation.AddressCleared() {
		_spec.ClearField(appclient.FieldAddress, field.TypeString)
	}
	if value, ok := _u.mutation.Building(); ok {
		_spec.SetField(appclient.FieldBuilding, field.TypeString, value)
	}
	if _u.mutation.BuildingCleared() {
		_spec.ClearField(appclient.FieldBuilding, field.TypeString)
	}
	if value, ok := _u.mutation.Tel(); ok {
		_spec.SetField(appclient.FieldTel, field.TypeString, value)
	}
	if _u.mutation.TelCleared() {
		_spec.ClearField(appclient.FieldTel, field.TypeString)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(appclient.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(appclient.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.AccessToken(); ok {
		_spec.SetField(appclient.FieldAccessToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.PrivateKey(); ok {
		_spec.SetField(appclient.FieldPrivateKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublicKey(); ok {
		_spec.SetField(appclient.FieldPublicKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Fingerprint(); ok {
		_spec.SetField(appclient.FieldFingerprint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(appclient.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(appclient.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StartAt(); ok {
		_spec.SetField(appclient.FieldStartAt, field.TypeTime, value)
	}
	if _u.mutation.StartAtCleared() {
		_spec.ClearField(appclient.FieldStartAt, field.TypeTime)
	}
	if value, ok := _u.mutation.StopAt(); ok {
		_spec.SetField(appclient.FieldStopAt, field.TypeTime, value)
	}
	if _u.mutation.StopAtCleared() {
		_spec.ClearField(appclient.FieldStopAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(appclient.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(appclient.FieldCreatedBy, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(appclient.FieldCreatedBy, field.TypeUint, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(appclient.FieldCreatedBy, field.TypeUint)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(appclient.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(appclient.FieldUpdatedBy, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(appclient.FieldUpdatedBy, field.TypeUint, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(appclient.FieldUpdatedBy, field.TypeUint)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(appclient.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(appclient.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(appclient.FieldDeletedBy, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(appclient.FieldDeletedBy, field.TypeUint, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(appclient.FieldDeletedBy, field.TypeUint)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(appclient.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(appclient.FieldVersion, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appclient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AppClientUpdateOne is the builder for updating a single AppClient entity.
type AppClientUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AppClientMutation
}

// SetName sets the "name" field.
func (_u *AppClientUpdateOne) SetName(v string) *AppClientUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AppClientUpdateOne) SetNillableName(v *string) *AppClientUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetIdentifier sets the "identifier" field.
func (_u *AppClientUpdateOne) SetIdentifier(v string) *AppClientUpdateOne {
	_u.mutation.SetIdentifier(v)
	return _u
}

// SetNillableIdentifier sets the "identifier" field if the given value is not nil.
func (_u *AppClientUpdateOne) SetNillableIdentifier(v *string) *AppClientUpdateOne {
	if v != nil {
		_u.SetIdentifier(*v)
	}
	return _u
}

// SetPostCode sets the "post_code" field.
func (_u *AppClientUpdateOne) SetPostCode(v string) *AppClientUpdateOne {
	_u.mutation.SetPostCode(v)
	return _u
}

// SetNillablePostCode sets the "post_code" field if the given value is not nil.
func (_u *AppClientUpdateOne) SetNillablePostCode(v *string) *AppClientUpdateOne {
	if v != nil {
		_u.SetPostCode(*v)
	}
	return _u
}

// ClearPostCode clears the value of the "post_code" field.
func (_u *AppClientUpdateOne) ClearPostCode() *AppClientUpdateOne {
	_u.mutation.ClearPostCode()
	return _u
}

// SetPref sets the "pref" field.
func (_u *AppClientUpdateOne) SetPref(v string) *AppClientUpdateOne {
	_u.mutation.SetPref(v)
	return _u
}

// SetNillablePref sets the "pref" field if the given value is not nil.
func (_u *AppClientUpdateOne) SetNillablePref(v *string) *AppClientUpdateOne {
	if v != nil {
		_u.SetPref(*v)
	}
	return _u
}

// ClearPref clears the value of the "pref" field.
func (_u *AppClientUpdateOne) ClearPref() *AppClientUpdateOne {
	_u.mutation.ClearPref()
	return _u
}

// SetCity sets the "city" field.
func (_u *AppClientUpdateOne) SetCity(v string) *AppClientUpdateOne {
	_u.mutation.SetCity(v)
	return _u
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_u *AppClientUpdateOne) SetNillableCity(v *string) *AppClientUpdateOne {
	if v != nil {
		_u.SetCity(*v)
	}
	return _u
}

// ClearCity clears the value of the "city" field.
func (_u *AppClientUpdateOne) ClearCity() *AppClientUpdateOne {
	_u.mutation.ClearCity()
	return _u
}

// SetAddress sets the "address" field.
func (_u *AppClientUpdateOne) SetAddress(v string) *AppClientUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *AppClientUpdateOne) SetNillableAddress(v *string) *AppClientUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// ClearAddress clears the value of the "address" field.
func (_u *AppClientUpdateOne) ClearAddress() *AppClientUpdateOne {
	_u.mutation.ClearAddress()
	return _u
}

// SetBuilding sets the "building" field.
func (_u *AppClientUpdateOne) SetBuilding(v string) *AppClientUpdateOne {
	_u.mutation.SetBuilding(v)
	return _u
}

// SetNillableBuilding sets the "building" field if the given value is not nil.
func (_u *AppClientUpdateOne) SetNillableBuilding(v *string) *AppClientUpdateOne {
	if v != nil {
		_u.SetBuilding(*v)
	}
	return _u
}

// ClearBuilding clears the value of the "building" field.
func (_u *AppClientUpdateOne) ClearBuilding() *AppClientUpdateOne {
	_u.mutation.ClearBuilding()
	return _u
}

// SetTel sets the "tel" field.
func (_u *AppClientUpdateOne) SetTel(v string) *AppClientUpdateOne {
	_u.mutation.SetTel(v)
	return _u
}

// SetNillableTel sets the "tel" field if the given value is not nil.
func (_u *AppClientUpdateOne) SetNillableTel(v *string) *AppClientUpdateOne {
	if v != nil {
		_u.SetTel(*v)
	}
	return _u
}

// ClearTel clears the value of the "tel" field.
func (_u *AppClientUpdateOne) ClearTel() *AppClientUpdateOne {
	_u.mutation.ClearTel()
	return _u
}

// SetEmail sets the "email" field.
func (_u *AppClientUpdateOne) SetEmail(v string) *AppClientUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *AppClientUpdateOne) SetNillableEmail(v *string) *AppClientUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *AppClientUpdateOne) ClearEmail() *AppClientUpdateOne {
	_u.mutation.ClearEmail()
	return _u
}

// SetAccessToken sets the "access_token" field.
func (_u *AppClientUpdateOne) SetAccessToken(v string) *AppClientUpdateOne {
	_u.mutation.SetAccessToken(v)
	return _u
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (_u *AppClientUpdateOne) SetNillableAccessToken(v *string) *AppClientUpdateOne {
	if v != nil {
		_u.SetAccessToken(*v)
	}
	return _u
}

// SetPrivateKey sets the "private_key" field.
func (_u *AppClientUpdateOne) SetPrivateKey(v string) *AppClientUpdateOne {
	_u.mutation.SetPrivateKey(v)
	return _u
}

// SetNillablePrivateKey sets the "private_key" field if the given value is not nil.
func (_u *AppClientUpdateOne) SetNillablePrivateKey(v *string) *AppClientUpdateOne {
	if v != nil {
		_u.SetPrivateKey(*v)
	}
	return _u
}

// SetPublicKey sets the "public_key" field.
func (_u *AppClientUpdateOne) SetPublicKey(v string) *AppClientUpdateOne {
	_u.mutation.SetPublicKey(v)
	return _u
}

// SetNillablePublicKey sets the "public_key" field if the given value is not nil.
func (_u *AppClientUpdateOne) SetNillablePublicKey(v *string) *AppClientUpdateOne {
	if v != nil {
		_u.SetPublicKey(*v)
	}
	return _u
}

// SetFingerprint sets the "fingerprint" field.
func (_u *AppClientUpdateOne) SetFingerprint(v string) *AppClientUpdateOne {
	_u.mutation.SetFingerprint(v)
	return _u
}

// SetNillableFingerprint sets the "fingerprint" field if the given value is not nil.
func (_u *AppClientUpdateOne) SetNillableFingerprint(v *string) *AppClientUpdateOne {
	if v != nil {
		_u.SetFingerprint(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AppClientUpdateOne) SetStatus(v int) *AppClientUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AppClientUpdateOne) SetNillableStatus(v *int) *AppClientUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *AppClientUpdateOne) AddStatus(v int) *AppClientUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetStartAt sets the "start_at" field.
func (_u *AppClientUpdateOne) SetStartAt(v time.Time) *AppClientUpdateOne {
	_u.mutation.SetStartAt(v)
	return _u
}

// SetNillableStartAt sets the "start_at" field if the given value is not nil.
func (_u *AppClientUpdateOne) SetNillableStartAt(v *time.Time) *AppClientUpdateOne {
	if v != nil {
		_u.SetStartAt(*v)
	}
	return _u
}

// ClearStartAt clears the value of the "start_at" field.
func (_u *AppClientUpdateOne) ClearStartAt() *AppClientUpdateOne {
	_u.mutation.ClearStartAt()
	return _u
}

// SetStopAt sets the "stop_at" field.
func (_u *AppClientUpdateOne) SetStopAt(v time.Time) *AppClientUpdateOne {
	_u.mutation.SetStopAt(v)
	return _u
}

// SetNillableStopAt sets the "stop_at" field if the given value is not nil.
func (_u *AppClientUpdateOne) SetNillableStopAt(v *time.Time) *AppClientUpdateOne {
	if v != nil {
		_u.SetStopAt(*v)
	}
	return _u
}

// ClearStopAt clears the value of the "stop_at" field.
func (_u *AppClientUpdateOne) ClearStopAt() *AppClientUpdateOne {
	_u.mutation.ClearStopAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AppClientUpdateOne) SetCreatedAt(v time.Time) *AppClientUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AppClientUpdateOne) SetNillableCreatedAt(v *time.Time) *AppClientUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *AppClientUpdateOne) SetCreatedBy(v uint) *AppClientUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *AppClientUpdateOne) SetNillableCreatedBy(v *uint) *AppClientUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *AppClientUpdateOne) AddCreatedBy(v int) *AppClientUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *AppClientUpdateOne) ClearCreatedBy() *AppClientUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AppClientUpdateOne) SetUpdatedAt(v time.Time) *AppClientUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *AppClientUpdateOne) SetNillableUpdatedAt(v *time.Time) *AppClientUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *AppClientUpdateOne) SetUpdatedBy(v uint) *AppClientUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *AppClientUpdateOne) SetNillableUpdatedBy(v *uint) *AppClientUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *AppClientUpdateOne) AddUpdatedBy(v int) *AppClientUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *AppClientUpdateOne) ClearUpdatedBy() *AppClientUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AppClientUpdateOne) SetDeletedAt(v time.Time) *AppClientUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AppClientUpdateOne) SetNillableDeletedAt(v *time.Time) *AppClientUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AppClientUpdateOne) ClearDeletedAt() *AppClientUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *AppClientUpdateOne) SetDeletedBy(v uint) *AppClientUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *AppClientUpdateOne) SetNillableDeletedBy(v *uint) *AppClientUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *AppClientUpdateOne) AddDeletedBy(v int) *AppClientUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *AppClientUpdateOne) ClearDeletedBy() *AppClientUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetVersion sets the "version" field.
func (_u *AppClientUpdateOne) SetVersion(v int) *AppClientUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *AppClientUpdateOne) SetNillableVersion(v *int) *AppClientUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *AppClientUpdateOne) AddVersion(v int) *AppClientUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the AppClientMutation object of the builder.
func (_u *AppClientUpdateOne) Mutation() *AppClientMutation {
	return _u.mutation
}

// Where appends a list predicates to the AppClientUpdate builder.
func (_u *AppClientUpdateOne) Where(ps ...predicate.AppClient) *AppClientUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AppClientUpdateOne) Select(field string, fields ...string) *AppClientUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AppClient entity.
func (_u *AppClientUpdateOne) Save(ctx context.Context) (*AppClient, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AppClientUpdateOne) SaveX(ctx context.Context) *AppClient {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AppClientUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AppClientUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AppClientUpdateOne) sqlSave(ctx context.Context) (_node *AppClient, err error) {
	_spec := sqlgraph.NewUpdateSpec(appclient.Table, appclient.Columns, sqlgraph.NewFieldSpec(appclient.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AppClient.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, appclient.FieldID)
		for _, f := range fields {
			if !appclient.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != appclient.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(appclient.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Identifier(); ok {
		_spec.SetField(appclient.FieldIdentifier, field.TypeString, value)
	}
	if value, ok := _u.mutation.PostCode(); ok {
		_spec.SetField(appclient.FieldPostCode, field.TypeString, value)
	}
	if _u.mutation.PostCodeCleared() {
		_spec.ClearField(appclient.FieldPostCode, field.TypeString)
	}
	if value, ok := _u.mutation.Pref(); ok {
		_spec.SetField(appclient.FieldPref, field.TypeString, value)
	}
	if _u.mutation.PrefCleared() {
		_spec.ClearField(appclient.FieldPref, field.TypeString)
	}
	if value, ok := _u.mutation.City(); ok {
		_spec.SetField(appclient.FieldCity, field.TypeString, value)
	}
	if _u.mutation.CityCleared() {
		_spec.ClearField(appclient.FieldCity, field.TypeString)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(appclient.FieldAddress, field.TypeString, value)
	}
	if _u.mutation.AddressCleared() {
		_spec.ClearField(appclient.FieldAddress, field.TypeString)
	}
	if value, ok := _u.mutation.Building(); ok {
		_spec.SetField(appclient.FieldBuilding, field.TypeString, value)
	}
	if _u.mutation.BuildingCleared() {
		_spec.ClearField(appclient.FieldBuilding, field.TypeString)
	}
	if value, ok := _u.mutation.Tel(); ok {
		_spec.SetField(appclient.FieldTel, field.TypeString, value)
	}
	if _u.mutation.TelCleared() {
		_spec.ClearField(appclient.FieldTel, field.TypeString)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(appclient.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(appclient.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.AccessToken(); ok {
		_spec.SetField(appclient.FieldAccessToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.PrivateKey(); ok {
		_spec.SetField(appclient.FieldPrivateKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublicKey(); ok {
		_spec.SetField(appclient.FieldPublicKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Fingerprint(); ok {
		_spec.SetField(appclient.FieldFingerprint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(appclient.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(appclient.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StartAt(); ok {
		_spec.SetField(appclient.FieldStartAt, field.TypeTime, value)
	}
	if _u.mutation.StartAtCleared() {
		_spec.ClearField(appclient.FieldStartAt, field.TypeTime)
	}
	if value, ok := _u.mutation.StopAt(); ok {
		_spec.SetField(appclient.FieldStopAt, field.TypeTime, value)
	}
	if _u.mutation.StopAtCleared() {
		_spec.ClearField(appclient.FieldStopAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(appclient.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(appclient.FieldCreatedBy, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(appclient.FieldCreatedBy, field.TypeUint, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(appclient.FieldCreatedBy, field.TypeUint)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(appclient.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(appclient.FieldUpdatedBy, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(appclient.FieldUpdatedBy, field.TypeUint, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(appclient.FieldUpdatedBy, field.TypeUint)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(appclient.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(appclient.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(appclient.FieldDeletedBy, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(appclient.FieldDeletedBy, field.TypeUint, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(appclient.FieldDeletedBy, field.TypeUint)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(appclient.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(appclient.FieldVersion, field.TypeInt, value)
	}
	_node = &AppClient{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appclient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
