// Code generated by ent, DO NOT EDIT.

package ent

import (
	"authorization-go-echo/ent/invitation"
	"authorization-go-echo/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InvitationUpdate is the builder for updating Invitation entities.
type InvitationUpdate struct {
	config
	hooks    []Hook
	mutation *InvitationMutation
}

// Where appends a list predicates to the InvitationUpdate builder.
func (_u *InvitationUpdate) Where(ps ...predicate.Invitation) *InvitationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetToken sets the "token" field.
func (_u *InvitationUpdate) SetToken(v string) *InvitationUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *InvitationUpdate) SetNillableToken(v *string) *InvitationUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *InvitationUpdate) SetRole(v int) *InvitationUpdate {
	_u.mutation.ResetRole()
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *InvitationUpdate) SetNillableRole(v *int) *InvitationUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// AddRole adds v to the "role" field.
func (_u *InvitationUpdate) AddRole(v int) *InvitationUpdate {
	_u.mutation.AddRole(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *InvitationUpdate) SetCreatedAt(v time.Time) *InvitationUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *InvitationUpdate) SetNillableCreatedAt(v *time.Time) *InvitationUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *InvitationUpdate) SetCreatedBy(v uint) *InvitationUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *InvitationUpdate) SetNillableCreatedBy(v *uint) *InvitationUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *InvitationUpdate) AddCreatedBy(v int) *InvitationUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *InvitationUpdate) ClearCreatedBy() *InvitationUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InvitationUpdate) SetUpdatedAt(v time.Time) *InvitationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *InvitationUpdate) SetNillableUpdatedAt(v *time.Time) *InvitationUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *InvitationUpdate) SetUpdatedBy(v uint) *InvitationUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *InvitationUpdate) SetNillableUpdatedBy(v *uint) *InvitationUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *InvitationUpdate) AddUpdatedBy(v int) *InvitationUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *InvitationUpdate) ClearUpdatedBy() *InvitationUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *InvitationUpdate) SetDeletedAt(v time.Time) *InvitationUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *InvitationUpdate) SetNillableDeletedAt(v *time.Time) *InvitationUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *InvitationUpdate) ClearDeletedAt() *InvitationUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *InvitationUpdate) SetDeletedBy(v uint) *InvitationUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *InvitationUpdate) SetNillableDeletedBy(v *uint) *InvitationUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *InvitationUpdate) AddDeletedBy(v int) *InvitationUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *InvitationUpdate) ClearDeletedBy() *InvitationUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetVersion sets the "version" field.
func (_u *InvitationUpdate) SetVersion(v int) *InvitationUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *InvitationUpdate) SetNillableVersion(v *int) *InvitationUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *InvitationUpdate) AddVersion(v int) *InvitationUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the InvitationMutation object of the builder.
func (_u *InvitationUpdate) Mutation() *InvitationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InvitationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvitationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InvitationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvitationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *InvitationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(invitation.Table, invitation.Columns, sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeUint))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(invitation.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(invitation.FieldRole, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRole(); ok {
		_spec.AddField(invitation.FieldRole, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(invitation.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(invitation.FieldCreatedBy, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(invitation.FieldCreatedBy, field.TypeUint, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(invitation.FieldCreatedBy, field.TypeUint)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invitation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(invitation.FieldUpdatedBy, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(invitation.FieldUpdatedBy, field.TypeUint, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(invitation.FieldUpdatedBy, field.TypeUint)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(invitation.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(invitation.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(invitation.FieldDeletedBy, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(invitation.FieldDeletedBy, field.TypeUint, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(invitation.FieldDeletedBy, field.TypeUint)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(invitation.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(invitation.FieldVersion, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invitation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InvitationUpdateOne is the builder for updating a single Invitation entity.
type InvitationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InvitationMutation
}

// SetToken sets the "token" field.
func (_u *InvitationUpdateOne) SetToken(v string) *InvitationUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *InvitationUpdateOne) SetNillableToken(v *string) *InvitationUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *InvitationUpdateOne) SetRole(v int) *InvitationUpdateOne {
	_u.mutation.ResetRole()
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *InvitationUpdateOne) SetNillableRole(v *int) *InvitationUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// AddRole adds v to the "role" field.
func (_u *InvitationUpdateOne) AddRole(v int) *InvitationUpdateOne {
	_u.mutation.AddRole(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *InvitationUpdateOne) SetCreatedAt(v time.Time) *InvitationUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *InvitationUpdateOne) SetNillableCreatedAt(v *time.Time) *InvitationUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *InvitationUpdateOne) SetCreatedBy(v uint) *InvitationUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *InvitationUpdateOne) SetNillableCreatedBy(v *uint) *InvitationUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *InvitationUpdateOne) AddCreatedBy(v int) *InvitationUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *InvitationUpdateOne) ClearCreatedBy() *InvitationUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InvitationUpdateOne) SetUpdatedAt(v time.Time) *InvitationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *InvitationUpdateOne) SetNillableUpdatedAt(v *time.Time) *InvitationUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *InvitationUpdateOne) SetUpdatedBy(v uint) *InvitationUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *InvitationUpdateOne) SetNillableUpdatedBy(v *uint) *InvitationUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *InvitationUpdateOne) AddUpdatedBy(v int) *InvitationUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *InvitationUpdateOne) ClearUpdatedBy() *InvitationUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *InvitationUpdateOne) SetDeletedAt(v time.Time) *InvitationUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *InvitationUpdateOne) SetNillableDeletedAt(v *time.Time) *InvitationUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *InvitationUpdateOne) ClearDeletedAt() *InvitationUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *InvitationUpdateOne) SetDeletedBy(v uint) *InvitationUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *InvitationUpdateOne) SetNillableDeletedBy(v *uint) *InvitationUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *InvitationUpdateOne) AddDeletedBy(v int) *InvitationUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *InvitationUpdateOne) ClearDeletedBy() *InvitationUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetVersion sets the "version" field.
func (_u *InvitationUpdateOne) SetVersion(v int) *InvitationUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *InvitationUpdateOne) SetNillableVersion(v *int) *InvitationUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *InvitationUpdateOne) AddVersion(v int) *InvitationUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the InvitationMutation object of the builder.
func (_u *InvitationUpdateOne) Mutation() *InvitationMutation {
	return _u.mutation
}

// Where appends a list predicates to the InvitationUpdate builder.
func (_u *InvitationUpdateOne) Where(ps ...predicate.Invitation) *InvitationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InvitationUpdateOne) Select(field string, fields ...string) *InvitationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Invitation entity.
func (_u *InvitationUpdateOne) Save(ctx context.Context) (*Invitation, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvitationUpdateOne) SaveX(ctx context.Context) *Invitation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InvitationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvitationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *InvitationUpdateOne) sqlSave(ctx context.Context) (_node *Invitation, err error) {
	_spec := sqlgraph.NewUpdateSpec(invitation.Table, invitation.Columns, sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeUint))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Invitation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invitation.FieldID)
		for _, f := range fields {
			if !invitation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invitation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(invitation.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(invitation.FieldRole, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRole(); ok {
		_spec.AddField(invitation.FieldRole, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(invitation.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(invitation.FieldCreatedBy, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(invitation.FieldCreatedBy, field.TypeUint, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(invitation.FieldCreatedBy, field.TypeUint)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invitation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(invitation.FieldUpdatedBy, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(invitation.FieldUpdatedBy, field.TypeUint, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(invitation.FieldUpdatedBy, field.TypeUint)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(invitation.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(invitation.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(invitation.FieldDeletedBy, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(invitation.FieldDeletedBy, field.TypeUint, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(invitation.FieldDeletedBy, field.TypeUint)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(invitation.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(invitation.FieldVersion, field.TypeInt, value)
	}
	_node = &Invitation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invitation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
