// Code generated by ent, DO NOT EDIT.

package ent

import (
	"authorization-go-echo/ent/notification"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NotificationCreate is the builder for creating a Notification entity.
type NotificationCreate struct {
	config
	mutation *NotificationMutation
	hooks    []Hook
}

// SetStaffID sets the "staff_id" field.
func (_c *NotificationCreate) SetStaffID(v uint) *NotificationCreate {
	_c.mutation.SetStaffID(v)
	return _c
}

// SetMessageType sets the "message_type" field.
func (_c *NotificationCreate) SetMessageType(v int) *NotificationCreate {
	_c.mutation.SetMessageType(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *NotificationCreate) SetTitle(v string) *NotificationCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetMessage sets the "message" field.
func (_c *NotificationCreate) SetMessage(v string) *NotificationCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *NotificationCreate) SetURL(v string) *NotificationCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableURL(v *string) *NotificationCreate {
	if v != nil {
		_c.SetURL(*v)
	}
	return _c
}

// SetRead sets the "read" field.
func (_c *NotificationCreate) SetRead(v bool) *NotificationCreate {
	_c.mutation.SetRead(v)
	return _c
}

// SetNillableRead sets the "read" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableRead(v *bool) *NotificationCreate {
	if v != nil {
		_c.SetRead(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *NotificationCreate) SetCreatedAt(v time.Time) *NotificationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableCreatedAt(v *time.Time) *NotificationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *NotificationCreate) SetCreatedBy(v uint) *NotificationCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableCreatedBy(v *uint) *NotificationCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *NotificationCreate) SetUpdatedAt(v time.Time) *NotificationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableUpdatedAt(v *time.Time) *NotificationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *NotificationCreate) SetUpdatedBy(v uint) *NotificationCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableUpdatedBy(v *uint) *NotificationCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *NotificationCreate) SetDeletedAt(v time.Time) *NotificationCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableDeletedAt(v *time.Time) *NotificationCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *NotificationCreate) SetDeletedBy(v uint) *NotificationCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableDeletedBy(v *uint) *NotificationCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *NotificationCreate) SetVersion(v int) *NotificationCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableVersion(v *int) *NotificationCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *NotificationCreate) SetID(v uint64) *NotificationCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the NotificationMutation object of the builder.
func (_c *NotificationCreate) Mutation() *NotificationMutation {
	return _c.mutation
}

// Save creates the Notification in the database.
func (_c *NotificationCreate) Save(ctx context.Context) (*Notification, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NotificationCreate) SaveX(ctx context.Context) *Notification {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NotificationCreate) defaults() {
	if _, ok := _c.mutation.Read(); !ok {
		v := notification.DefaultRead
		_c.mutation.SetRead(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := notification.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := notification.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := notification.DefaultVersion
		_c.mutation.SetVersion(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NotificationCreate) check() error {
	if _, ok := _c.mutation.StaffID(); !ok {
		return &ValidationError{Name: "staff_id", err: errors.New(`ent: missing required field "Notification.staff_id"`)}
	}
	if _, ok := _c.mutation.MessageType(); !ok {
		return &ValidationError{Name: "message_type", err: errors.New(`ent: missing required field "Notification.message_type"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Notification.title"`)}
	}
	if _, ok := _c.mutation.Message(); !ok {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required field "Notification.message"`)}
	}
	if _, ok := _c.mutation.Read(); !ok {
		return &ValidationError{Name: "read", err: errors.New(`ent: missing required field "Notification.read"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Notification.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Notification.updated_at"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Notification.version"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := notification.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Notification.id": %w`, err)}
		}
	}
	return nil
}

func (_c *NotificationCreate) sqlSave(ctx context.Context) (*Notification, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NotificationCreate) createSpec() (*Notification, *sqlgraph.CreateSpec) {
	var (
		_node = &Notification{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(notification.Table, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.StaffID(); ok {
		_spec.SetField(notification.FieldStaffID, field.TypeUint, value)
		_node.StaffID = value
	}
	if value, ok := _c.mutation.MessageType(); ok {
		_spec.SetField(notification.FieldMessageType, field.TypeInt, value)
		_node.MessageType = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(notification.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(notification.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(notification.FieldURL, field.TypeString, value)
		_node.URL = &value
	}
	if value, ok := _c.mutation.Read(); ok {
		_spec.SetField(notification.FieldRead, field.TypeBool, value)
		_node.Read = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(notification.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(notification.FieldCreatedBy, field.TypeUint, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(notification.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(notification.FieldUpdatedBy, field.TypeUint, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(notification.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(notification.FieldDeletedBy, field.TypeUint, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(notification.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	return _node, _spec
}

// NotificationCreateBulk is the builder for creating many Notification entities in bulk.
type NotificationCreateBulk struct {
	config
	err      error
	builders []*NotificationCreate
}

// Save creates the Notification entities in the database.
func (_c *NotificationCreateBulk) Save(ctx context.Context) ([]*Notification, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Notification, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NotificationCreateBulk) SaveX(ctx context.Context) []*Notification {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
