// Code generated by ent, DO NOT EDIT.

package ent

import (
	"authorization-go-echo/ent/notification"
	"authorization-go-echo/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NotificationUpdate is the builder for updating Notification entities.
type NotificationUpdate struct {
	config
	hooks    []Hook
	mutation *NotificationMutation
}

// Where appends a list predicates to the NotificationUpdate builder.
func (_u *NotificationUpdate) Where(ps ...predicate.Notification) *NotificationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStaffID sets the "staff_id" field.
func (_u *NotificationUpdate) SetStaffID(v uint) *NotificationUpdate {
	_u.mutation.ResetStaffID()
	_u.mutation.SetStaffID(v)
	return _u
}

// SetNillableStaffID sets the "staff_id" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableStaffID(v *uint) *NotificationUpdate {
	if v != nil {
		_u.SetStaffID(*v)
	}
	return _u
}

// AddStaffID adds value to the "staff_id" field.
func (_u *NotificationUpdate) AddStaffID(v int) *NotificationUpdate {
	_u.mutation.AddStaffID(v)
	return _u
}

// SetMessageType sets the "message_type" field.
func (_u *NotificationUpdate) SetMessageType(v int) *NotificationUpdate {
	_u.mutation.ResetMessageType()
	_u.mutation.SetMessageType(v)
	return _u
}

// SetNillableMessageType sets the "message_type" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableMessageType(v *int) *NotificationUpdate {
	if v != nil {
		_u.SetMessageType(*v)
	}
	return _u
}

// AddMessageType adds value to the "message_type" field.
func (_u *NotificationUpdate) AddMessageType(v int) *NotificationUpdate {
	_u.mutation.AddMessageType(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *NotificationUpdate) SetTitle(v string) *NotificationUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableTitle(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *NotificationUpdate) SetMessage(v string) *NotificationUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableMessage(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *NotificationUpdate) SetURL(v string) *NotificationUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableURL(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *NotificationUpdate) ClearURL() *NotificationUpdate {
	_u.mutation.ClearURL()
	return _u
}

// SetRead sets the "read" field.
func (_u *NotificationUpdate) SetRead(v bool) *NotificationUpdate {
	_u.mutation.SetRead(v)
	return _u
}

// SetNillableRead sets the "read" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableRead(v *bool) *NotificationUpdate {
	if v != nil {
		_u.SetRead(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *NotificationUpdate) SetCreatedAt(v time.Time) *NotificationUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableCreatedAt(v *time.Time) *NotificationUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *NotificationUpdate) SetCreatedBy(v uint) *NotificationUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableCreatedBy(v *uint) *NotificationUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *NotificationUpdate) AddCreatedBy(v int) *NotificationUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *NotificationUpdate) ClearCreatedBy() *NotificationUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotificationUpdate) SetUpdatedAt(v time.Time) *NotificationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableUpdatedAt(v *time.Time) *NotificationUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *NotificationUpdate) SetUpdatedBy(v uint) *NotificationUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableUpdatedBy(v *uint) *NotificationUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *NotificationUpdate) AddUpdatedBy(v int) *NotificationUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *NotificationUpdate) ClearUpdatedBy() *NotificationUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *NotificationUpdate) SetDeletedAt(v time.Time) *NotificationUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableDeletedAt(v *time.Time) *NotificationUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *NotificationUpdate) ClearDeletedAt() *NotificationUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *NotificationUpdate) SetDeletedBy(v uint) *NotificationUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableDeletedBy(v *uint) *NotificationUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *NotificationUpdate) AddDeletedBy(v int) *NotificationUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *NotificationUpdate) ClearDeletedBy() *NotificationUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetVersion sets the "version" field.
func (_u *NotificationUpdate) SetVersion(v int) *NotificationUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableVersion(v *int) *NotificationUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *NotificationUpdate) AddVersion(v int) *NotificationUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the NotificationMutation object of the builder.
func (_u *NotificationUpdate) Mutation() *NotificationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotificationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotificationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *NotificationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StaffID(); ok {
		_spec.SetField(notification.FieldStaffID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedStaffID(); ok {
		_spec.AddField(notification.FieldStaffID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.MessageType(); ok {
		_spec.SetField(notification.FieldMessageType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMessageType(); ok {
		_spec.AddField(notification.FieldMessageType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(notification.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(notification.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(notification.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(notification.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.Read(); ok {
		_spec.SetField(notification.FieldRead, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(notification.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(notification.FieldCreatedBy, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(notification.FieldCreatedBy, field.TypeUint, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(notification.FieldCreatedBy, field.TypeUint)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notification.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(notification.FieldUpdatedBy, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(notification.FieldUpdatedBy, field.TypeUint, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(notification.FieldUpdatedBy, field.TypeUint)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(notification.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(notification.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(notification.FieldDeletedBy, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(notification.FieldDeletedBy, field.TypeUint, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(notification.FieldDeletedBy, field.TypeUint)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(notification.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(notification.FieldVersion, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotificationUpdateOne is the builder for updating a single Notification entity.
type NotificationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotificationMutation
}

// SetStaffID sets the "staff_id" field.
func (_u *NotificationUpdateOne) SetStaffID(v uint) *NotificationUpdateOne {
	_u.mutation.ResetStaffID()
	_u.mutation.SetStaffID(v)
	return _u
}

// SetNillableStaffID sets the "staff_id" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableStaffID(v *uint) *NotificationUpdateOne {
	if v != nil {
		_u.SetStaffID(*v)
	}
	return _u
}

// AddStaffID adds value to the "staff_id" field.
func (_u *NotificationUpdateOne) AddStaffID(v int) *NotificationUpdateOne {
	_u.mutation.AddStaffID(v)
	return _u
}

// SetMessageType sets the "message_type" field.
func (_u *NotificationUpdateOne) SetMessageType(v int) *NotificationUpdateOne {
	_u.mutation.ResetMessageType()
	_u.mutation.SetMessageType(v)
	return _u
}

// SetNillableMessageType sets the "message_type" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableMessageType(v *int) *NotificationUpdateOne {
	if v != nil {
		_u.SetMessageType(*v)
	}
	return _u
}

// AddMessageType adds value to the "message_type" field.
func (_u *NotificationUpdateOne) AddMessageType(v int) *NotificationUpdateOne {
	_u.mutation.AddMessageType(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *NotificationUpdateOne) SetTitle(v string) *NotificationUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableTitle(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *NotificationUpdateOne) SetMessage(v string) *NotificationUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableMessage(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *NotificationUpdateOne) SetURL(v string) *NotificationUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableURL(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *NotificationUpdateOne) ClearURL() *NotificationUpdateOne {
	_u.mutation.ClearURL()
	return _u
}

// SetRead sets the "read" field.
func (_u *NotificationUpdateOne) SetRead(v bool) *NotificationUpdateOne {
	_u.mutation.SetRead(v)
	return _u
}

// SetNillableRead sets the "read" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableRead(v *bool) *NotificationUpdateOne {
	if v != nil {
		_u.SetRead(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *NotificationUpdateOne) SetCreatedAt(v time.Time) *NotificationUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableCreatedAt(v *time.Time) *NotificationUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *NotificationUpdateOne) SetCreatedBy(v uint) *NotificationUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableCreatedBy(v *uint) *NotificationUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *NotificationUpdateOne) AddCreatedBy(v int) *NotificationUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *NotificationUpdateOne) ClearCreatedBy() *NotificationUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotificationUpdateOne) SetUpdatedAt(v time.Time) *NotificationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableUpdatedAt(v *time.Time) *NotificationUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *NotificationUpdateOne) SetUpdatedBy(v uint) *NotificationUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableUpdatedBy(v *uint) *NotificationUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *NotificationUpdateOne) AddUpdatedBy(v int) *NotificationUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *NotificationUpdateOne) ClearUpdatedBy() *NotificationUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *NotificationUpdateOne) SetDeletedAt(v time.Time) *NotificationUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableDeletedAt(v *time.Time) *NotificationUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *NotificationUpdateOne) ClearDeletedAt() *NotificationUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *NotificationUpdateOne) SetDeletedBy(v uint) *NotificationUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableDeletedBy(v *uint) *NotificationUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *NotificationUpdateOne) AddDeletedBy(v int) *NotificationUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *NotificationUpdateOne) ClearDeletedBy() *NotificationUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetVersion sets the "version" field.
func (_u *NotificationUpdateOne) SetVersion(v int) *NotificationUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableVersion(v *int) *NotificationUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *NotificationUpdateOne) AddVersion(v int) *NotificationUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the NotificationMutation object of the builder.
func (_u *NotificationUpdateOne) Mutation() *NotificationMutation {
	return _u.mutation
}

// Where appends a list predicates to the NotificationUpdate builder.
func (_u *NotificationUpdateOne) Where(ps ...predicate.Notification) *NotificationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotificationUpdateOne) Select(field string, fields ...string) *NotificationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Notification entity.
func (_u *NotificationUpdateOne) Save(ctx context.Context) (*Notification, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationUpdateOne) SaveX(ctx context.Context) *Notification {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotificationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *NotificationUpdateOne) sqlSave(ctx context.Context) (_node *Notification, err error) {
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Notification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notification.FieldID)
		for _, f := range fields {
			if !notification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StaffID(); ok {
		_spec.SetField(notification.FieldStaffID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedStaffID(); ok {
		_spec.AddField(notification.FieldStaffID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.MessageType(); ok {
		_spec.SetField(notification.FieldMessageType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMessageType(); ok {
		_spec.AddField(notification.FieldMessageType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(notification.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(notification.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(notification.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(notification.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.Read(); ok {
		_spec.SetField(notification.FieldRead, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(notification.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(notification.FieldCreatedBy, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(notification.FieldCreatedBy, field.TypeUint, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(notification.FieldCreatedBy, field.TypeUint)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notification.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(notification.FieldUpdatedBy, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(notification.FieldUpdatedBy, field.TypeUint, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(notification.FieldUpdatedBy, field.TypeUint)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(notification.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(notification.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(notification.FieldDeletedBy, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(notification.FieldDeletedBy, field.TypeUint, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(notification.FieldDeletedBy, field.TypeUint)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(notification.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(notification.FieldVersion, field.TypeInt, value)
	}
	_node = &Notification{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
