// Code generated by ent, DO NOT EDIT.

package ent

import (
	"authorization-go-echo/ent/appclient"
	"authorization-go-echo/ent/invitation"
	"authorization-go-echo/ent/notification"
	"authorization-go-echo/ent/schema"
	"authorization-go-echo/ent/staff"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appclientFields := schema.AppClient{}.Fields()
	_ = appclientFields
	// appclientDescStatus is the schema descriptor for status field.
	appclientDescStatus := appclientFields[14].Descriptor()
	// appclient.DefaultStatus holds the default value on creation for the status field.
	appclient.DefaultStatus = appclientDescStatus.Default.(int)
	// appclientDescCreatedAt is the schema descriptor for created_at field.
	appclientDescCreatedAt := appclientFields[17].Descriptor()
	// appclient.DefaultCreatedAt holds the default value on creation for the created_at field.
	appclient.DefaultCreatedAt = appclientDescCreatedAt.Default.(func() time.Time)
	// appclientDescUpdatedAt is the schema descriptor for updated_at field.
	appclientDescUpdatedAt := appclientFields[19].Descriptor()
	// appclient.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	appclient.DefaultUpdatedAt = appclientDescUpdatedAt.Default.(func() time.Time)
	// appclientDescVersion is the schema descriptor for version field.
	appclientDescVersion := appclientFields[23].Descriptor()
	// appclient.DefaultVersion holds the default value on creation for the version field.
	appclient.DefaultVersion = appclientDescVersion.Default.(int)
	// appclientDescID is the schema descriptor for id field.
	appclientDescID := appclientFields[0].Descriptor()
	// appclient.IDValidator is a validator for the "id" field. It is called by the builders before save.
	appclient.IDValidator = appclientDescID.Validators[0].(func(uint64) error)
	invitationFields := schema.Invitation{}.Fields()
	_ = invitationFields
	// invitationDescCreatedAt is the schema descriptor for created_at field.
	invitationDescCreatedAt := invitationFields[2].Descriptor()
	// invitation.DefaultCreatedAt holds the default value on creation for the created_at field.
	invitation.DefaultCreatedAt = invitationDescCreatedAt.Default.(func() time.Time)
	// invitationDescUpdatedAt is the schema descriptor for updated_at field.
	invitationDescUpdatedAt := invitationFields[4].Descriptor()
	// invitation.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	invitation.DefaultUpdatedAt = invitationDescUpdatedAt.Default.(func() time.Time)
	// invitationDescVersion is the schema descriptor for version field.
	invitationDescVersion := invitationFields[8].Descriptor()
	// invitation.DefaultVersion holds the default value on creation for the version field.
	invitation.DefaultVersion = invitationDescVersion.Default.(int)
	// invitationDescID is the schema descriptor for id field.
	invitationDescID := invitationFields[0].Descriptor()
	// invitation.IDValidator is a validator for the "id" field. It is called by the builders before save.
	invitation.IDValidator = invitationDescID.Validators[0].(func(uint) error)
	notificationFields := schema.Notification{}.Fields()
	_ = notificationFields
	// notificationDescRead is the schema descriptor for read field.
	notificationDescRead := notificationFields[6].Descriptor()
	// notification.DefaultRead holds the default value on creation for the read field.
	notification.DefaultRead = notificationDescRead.Default.(bool)
	// notificationDescCreatedAt is the schema descriptor for created_at field.
	notificationDescCreatedAt := notificationFields[7].Descriptor()
	// notification.DefaultCreatedAt holds the default value on creation for the created_at field.
	notification.DefaultCreatedAt = notificationDescCreatedAt.Default.(func() time.Time)
	// notificationDescUpdatedAt is the schema descriptor for updated_at field.
	notificationDescUpdatedAt := notificationFields[9].Descriptor()
	// notification.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	notification.DefaultUpdatedAt = notificationDescUpdatedAt.Default.(func() time.Time)
	// notificationDescVersion is the schema descriptor for version field.
	notificationDescVersion := notificationFields[13].Descriptor()
	// notification.DefaultVersion holds the default value on creation for the version field.
	notification.DefaultVersion = notificationDescVersion.Default.(int)
	// notificationDescID is the schema descriptor for id field.
	notificationDescID := notificationFields[0].Descriptor()
	// notification.IDValidator is a validator for the "id" field. It is called by the builders before save.
	notification.IDValidator = notificationDescID.Validators[0].(func(uint64) error)
	staffFields := schema.Staff{}.Fields()
	_ = staffFields
	// staffDescRole is the schema descriptor for role field.
	staffDescRole := staffFields[6].Descriptor()
	// staff.DefaultRole holds the default value on creation for the role field.
	staff.DefaultRole = staffDescRole.Default.(int)
	// staffDescCreatedAt is the schema descriptor for created_at field.
	staffDescCreatedAt := staffFields[8].Descriptor()
	// staff.DefaultCreatedAt holds the default value on creation for the created_at field.
	staff.DefaultCreatedAt = staffDescCreatedAt.Default.(func() time.Time)
	// staffDescUpdatedAt is the schema descriptor for updated_at field.
	staffDescUpdatedAt := staffFields[10].Descriptor()
	// staff.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	staff.DefaultUpdatedAt = staffDescUpdatedAt.Default.(func() time.Time)
	// staffDescVersion is the schema descriptor for version field.
	staffDescVersion := staffFields[14].Descriptor()
	// staff.DefaultVersion holds the default value on creation for the version field.
	staff.DefaultVersion = staffDescVersion.Default.(int)
	// staffDescID is the schema descriptor for id field.
	staffDescID := staffFields[0].Descriptor()
	// staff.IDValidator is a validator for the "id" field. It is called by the builders before save.
	staff.IDValidator = staffDescID.Validators[0].(func(uint) error)
}
