// Code generated by ent, DO NOT EDIT.

package ent

import (
	"authorization-go-echo/ent/predicate"
	"authorization-go-echo/ent/staff"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StaffUpdate is the builder for updating Staff entities.
type StaffUpdate struct {
	config
	hooks    []Hook
	mutation *StaffMutation
}

// Where appends a list predicates to the StaffUpdate builder.
func (_u *StaffUpdate) Where(ps ...predicate.Staff) *StaffUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *StaffUpdate) SetName(v string) *StaffUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *StaffUpdate) SetNillableName(v *string) *StaffUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *StaffUpdate) SetEmail(v string) *StaffUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *StaffUpdate) SetNillableEmail(v *string) *StaffUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *StaffUpdate) SetProvider(v int) *StaffUpdate {
	_u.mutation.ResetProvider()
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *StaffUpdate) SetNillableProvider(v *int) *StaffUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// AddProvider adds value to the "provider" field.
func (_u *StaffUpdate) AddProvider(v int) *StaffUpdate {
	_u.mutation.AddProvider(v)
	return _u
}

// SetProviderID sets the "provider_id" field.
func (_u *StaffUpdate) SetProviderID(v string) *StaffUpdate {
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *StaffUpdate) SetNillableProviderID(v *string) *StaffUpdate {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// SetAvatar sets the "avatar" field.
func (_u *StaffUpdate) SetAvatar(v string) *StaffUpdate {
	_u.mutation.SetAvatar(v)
	return _u
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (_u *StaffUpdate) SetNillableAvatar(v *string) *StaffUpdate {
	if v != nil {
		_u.SetAvatar(*v)
	}
	return _u
}

// ClearAvatar clears the value of the "avatar" field.
func (_u *StaffUpdate) ClearAvatar() *StaffUpdate {
	_u.mutation.ClearAvatar()
	return _u
}

// SetRole sets the "role" field.
func (_u *StaffUpdate) SetRole(v int) *StaffUpdate {
	_u.mutation.ResetRole()
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *StaffUpdate) SetNillableRole(v *int) *StaffUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// AddRole adds value to the "role" field.
func (_u *StaffUpdate) AddRole(v int) *StaffUpdate {
	_u.mutation.AddRole(v)
	return _u
}

// SetLastLoginAt sets the "last_login_at" field.
func (_u *StaffUpdate) SetLastLoginAt(v time.Time) *StaffUpdate {
	_u.mutation.SetLastLoginAt(v)
	return _u
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_u *StaffUpdate) SetNillableLastLoginAt(v *time.Time) *StaffUpdate {
	if v != nil {
		_u.SetLastLoginAt(*v)
	}
	return _u
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (_u *StaffUpdate) ClearLastLoginAt() *StaffUpdate {
	_u.mutation.ClearLastLoginAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *StaffUpdate) SetCreatedAt(v time.Time) *StaffUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *StaffUpdate) SetNillableCreatedAt(v *time.Time) *StaffUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *StaffUpdate) SetCreatedBy(v uint) *StaffUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *StaffUpdate) SetNillableCreatedBy(v *uint) *StaffUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *StaffUpdate) AddCreatedBy(v int) *StaffUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *StaffUpdate) ClearCreatedBy() *StaffUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StaffUpdate) SetUpdatedAt(v time.Time) *StaffUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *StaffUpdate) SetNillableUpdatedAt(v *time.Time) *StaffUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *StaffUpdate) SetUpdatedBy(v uint) *StaffUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *StaffUpdate) SetNillableUpdatedBy(v *uint) *StaffUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *StaffUpdate) AddUpdatedBy(v int) *StaffUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *StaffUpdate) ClearUpdatedBy() *StaffUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *StaffUpdate) SetDeletedAt(v time.Time) *StaffUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *StaffUpdate) SetNillableDeletedAt(v *time.Time) *StaffUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *StaffUpdate) ClearDeletedAt() *StaffUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *StaffUpdate) SetDeletedBy(v uint) *StaffUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *StaffUpdate) SetNillableDeletedBy(v *uint) *StaffUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *StaffUpdate) AddDeletedBy(v int) *StaffUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *StaffUpdate) ClearDeletedBy() *StaffUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetVersion sets the "version" field.
func (_u *StaffUpdate) SetVersion(v int) *StaffUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *StaffUpdate) SetNillableVersion(v *int) *StaffUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *StaffUpdate) AddVersion(v int) *StaffUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the StaffMutation object of the builder.
func (_u *StaffUpdate) Mutation() *StaffMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StaffUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StaffUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StaffUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StaffUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *StaffUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(staff.Table, staff.Columns, sqlgraph.NewFieldSpec(staff.FieldID, field.TypeUint))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(staff.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(staff.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(staff.FieldProvider, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProvider(); ok {
		_spec.AddField(staff.FieldProvider, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ProviderID(); ok {
		_spec.SetField(staff.FieldProviderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Avatar(); ok {
		_spec.SetField(staff.FieldAvatar, field.TypeString, value)
	}
	if _u.mutation.AvatarCleared() {
		_spec.ClearField(staff.FieldAvatar, field.TypeString)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(staff.FieldRole, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRole(); ok {
		_spec.AddField(staff.FieldRole, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastLoginAt(); ok {
		_spec.SetField(staff.FieldLastLoginAt, field.TypeTime, value)
	}
	if _u.mutation.LastLoginAtCleared() {
		_spec.ClearField(staff.FieldLastLoginAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(staff.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(staff.FieldCreatedBy, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(staff.FieldCreatedBy, field.TypeUint, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(staff.FieldCreatedBy, field.TypeUint)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(staff.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(staff.FieldUpdatedBy, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(staff.FieldUpdatedBy, field.TypeUint, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(staff.FieldUpdatedBy, field.TypeUint)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(staff.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(staff.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(staff.FieldDeletedBy, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(staff.FieldDeletedBy, field.TypeUint, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(staff.FieldDeletedBy, field.TypeUint)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(staff.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(staff.FieldVersion, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{staff.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StaffUpdateOne is the builder for updating a single Staff entity.
type StaffUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StaffMutation
}

// SetName sets the "name" field.
func (_u *StaffUpdateOne) SetName(v string) *StaffUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *StaffUpdateOne) SetNillableName(v *string) *StaffUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *StaffUpdateOne) SetEmail(v string) *StaffUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *StaffUpdateOne) SetNillableEmail(v *string) *StaffUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *StaffUpdateOne) SetProvider(v int) *StaffUpdateOne {
	_u.mutation.ResetProvider()
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *StaffUpdateOne) SetNillableProvider(v *int) *StaffUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// AddProvider adds value to the "provider" field.
func (_u *StaffUpdateOne) AddProvider(v int) *StaffUpdateOne {
	_u.mutation.AddProvider(v)
	return _u
}

// SetProviderID sets the "provider_id" field.
func (_u *StaffUpdateOne) SetProviderID(v string) *StaffUpdateOne {
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *StaffUpdateOne) SetNillableProviderID(v *string) *StaffUpdateOne {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// SetAvatar sets the "avatar" field.
func (_u *StaffUpdateOne) SetAvatar(v string) *StaffUpdateOne {
	_u.mutation.SetAvatar(v)
	return _u
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (_u *StaffUpdateOne) SetNillableAvatar(v *string) *StaffUpdateOne {
	if v != nil {
		_u.SetAvatar(*v)
	}
	return _u
}

// ClearAvatar clears the value of the "avatar" field.
func (_u *StaffUpdateOne) ClearAvatar() *StaffUpdateOne {
	_u.mutation.ClearAvatar()
	return _u
}

// SetRole sets the "role" field.
func (_u *StaffUpdateOne) SetRole(v int) *StaffUpdateOne {
	_u.mutation.ResetRole()
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *StaffUpdateOne) SetNillableRole(v *int) *StaffUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// AddRole adds value to the "role" field.
func (_u *StaffUpdateOne) AddRole(v int) *StaffUpdateOne {
	_u.mutation.AddRole(v)
	return _u
}

// SetLastLoginAt sets the "last_login_at" field.
func (_u *StaffUpdateOne) SetLastLoginAt(v time.Time) *StaffUpdateOne {
	_u.mutation.SetLastLoginAt(v)
	return _u
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_u *StaffUpdateOne) SetNillableLastLoginAt(v *time.Time) *StaffUpdateOne {
	if v != nil {
		_u.SetLastLoginAt(*v)
	}
	return _u
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (_u *StaffUpdateOne) ClearLastLoginAt() *StaffUpdateOne {
	_u.mutation.ClearLastLoginAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *StaffUpdateOne) SetCreatedAt(v time.Time) *StaffUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *StaffUpdateOne) SetNillableCreatedAt(v *time.Time) *StaffUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *StaffUpdateOne) SetCreatedBy(v uint) *StaffUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *StaffUpdateOne) SetNillableCreatedBy(v *uint) *StaffUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *StaffUpdateOne) AddCreatedBy(v int) *StaffUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *StaffUpdateOne) ClearCreatedBy() *StaffUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StaffUpdateOne) SetUpdatedAt(v time.Time) *StaffUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *StaffUpdateOne) SetNillableUpdatedAt(v *time.Time) *StaffUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *StaffUpdateOne) SetUpdatedBy(v uint) *StaffUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *StaffUpdateOne) SetNillableUpdatedBy(v *uint) *StaffUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *StaffUpdateOne) AddUpdatedBy(v int) *StaffUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *StaffUpdateOne) ClearUpdatedBy() *StaffUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *StaffUpdateOne) SetDeletedAt(v time.Time) *StaffUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *StaffUpdateOne) SetNillableDeletedAt(v *time.Time) *StaffUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *StaffUpdateOne) ClearDeletedAt() *StaffUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *StaffUpdateOne) SetDeletedBy(v uint) *StaffUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *StaffUpdateOne) SetNillableDeletedBy(v *uint) *StaffUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *StaffUpdateOne) AddDeletedBy(v int) *StaffUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *StaffUpdateOne) ClearDeletedBy() *StaffUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetVersion sets the "version" field.
func (_u *StaffUpdateOne) SetVersion(v int) *StaffUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *StaffUpdateOne) SetNillableVersion(v *int) *StaffUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *StaffUpdateOne) AddVersion(v int) *StaffUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the StaffMutation object of the builder.
func (_u *StaffUpdateOne) Mutation() *StaffMutation {
	return _u.mutation
}

// Where appends a list predicates to the StaffUpdate builder.
func (_u *StaffUpdateOne) Where(ps ...predicate.Staff) *StaffUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StaffUpdateOne) Select(field string, fields ...string) *StaffUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Staff entity.
func (_u *StaffUpdateOne) Save(ctx context.Context) (*Staff, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StaffUpdateOne) SaveX(ctx context.Context) *Staff {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StaffUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StaffUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *StaffUpdateOne) sqlSave(ctx context.Context) (_node *Staff, err error) {
	_spec := sqlgraph.NewUpdateSpec(staff.Table, staff.Columns, sqlgraph.NewFieldSpec(staff.FieldID, field.TypeUint))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Staff.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, staff.FieldID)
		for _, f := range fields {
			if !staff.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != staff.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(staff.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(staff.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(staff.FieldProvider, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProvider(); ok {
		_spec.AddField(staff.FieldProvider, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ProviderID(); ok {
		_spec.SetField(staff.FieldProviderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Avatar(); ok {
		_spec.SetField(staff.FieldAvatar, field.TypeString, value)
	}
	if _u.mutation.AvatarCleared() {
		_spec.ClearField(staff.FieldAvatar, field.TypeString)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(staff.FieldRole, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRole(); ok {
		_spec.AddField(staff.FieldRole, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastLoginAt(); ok {
		_spec.SetField(staff.FieldLastLoginAt, field.TypeTime, value)
	}
	if _u.mutation.LastLoginAtCleared() {
		_spec.ClearField(staff.FieldLastLoginAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(staff.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(staff.FieldCreatedBy, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(staff.FieldCreatedBy, field.TypeUint, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(staff.FieldCreatedBy, field.TypeUint)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(staff.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(staff.FieldUpdatedBy, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(staff.FieldUpdatedBy, field.TypeUint, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(staff.FieldUpdatedBy, field.TypeUint)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(staff.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(staff.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(staff.FieldDeletedBy, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(staff.FieldDeletedBy, field.TypeUint, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(staff.FieldDeletedBy, field.TypeUint)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(staff.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(staff.FieldVersion, field.TypeInt, value)
	}
	_node = &Staff{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{staff.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
