networks:
  authorization:
    external: true

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: ${NGINX_CONTAINER}
    environment:
      - 'DHPARAM_GENERATION=false'
    ports:
      - '${NGINX_HTTPS_PORT}:443'
    volumes:
      - ./proxy/certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - mysql
      - redis
    networks:
      - authorization

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ${LETS_ENCRYPT_CONTAINER}
    environment:
      - NGINX_PROXY_CONTAINER=${NGINX_CONTAINER}
    volumes:
      - ./proxy/certs:/etc/nginx/certs:rw
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy
    networks:
      - authorization

  mysql:
    image: mysql:8.0
    container_name: ${MYSQL_CONTAINER}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${MYSQL_TZ}
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    networks:
      - authorization

  redis:
    image: redis:7.0
    container_name: ${REDIS_CONTAINER}
    ports:
      - '${REDIS_PORT}:6379'
    command: redis-server --appendonly yes
    volumes:
      - './data/redis:/data'
    networks:
      - authorization

  mailpit:
    image: axllent/mailpit:latest
    container_name: ${MAILPIT_CONTAINER}
    ports:
      - "${MAILPIT_SMTP_PORT}:1025"
      - "${MAILPIT_UI_PORT}:8025"
    networks:
      - authorization

  lambda:
    image: public.ecr.aws/lambda/provided:al2023
    platform: linux/amd64
    entrypoint: ["/bin/sh", "-c", "cp /var/task/bootstrap /var/runtime/bootstrap && chmod +x /var/runtime/bootstrap && exec /lambda-entrypoint.sh bootstrap"]
    restart: always
    volumes:
      - ../../../function:/var/task
    ports:
      - "${LAMBDA_PORT}:8080"
    environment:
      - INSECURE_SKIP_TLS_VERIFY=true
    networks:
      - authorization
    extra_hosts:
      - "apis.authorization-php.dev:172.19.0.6"
      - "apis.authorization-go.dev:172.19.0.6"
      - "apis.authorization-python.dev:172.19.0.6"
      - "apis.authorization-ts.dev:172.19.0.6"
    logging:
      options:
        max-size: "5m"
        max-file: "10"
