// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AppClient is the predicate function for appclient builders.
type AppClient func(*sql.Selector)

// Invitation is the predicate function for invitation builders.
type Invitation func(*sql.Selector)

// Notification is the predicate function for notification builders.
type Notification func(*sql.Selector)

// Staff is the predicate function for staff builders.
type Staff func(*sql.Selector)
