// Code generated by ent, DO NOT EDIT.

package appclient

import (
	"authorization-go-echo/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.AppClient {
	return predicate.AppClient(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.AppClient {
	return predicate.AppClient(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.AppClient {
	return predicate.AppClient(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.AppClient {
	return predicate.AppClient(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.AppClient {
	return predicate.AppClient(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.AppClient {
	return predicate.AppClient(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.AppClient {
	return predicate.AppClient(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldName, v))
}

// Identifier applies equality check predicate on the "identifier" field. It's identical to IdentifierEQ.
func Identifier(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldIdentifier, v))
}

// PostCode applies equality check predicate on the "post_code" field. It's identical to PostCodeEQ.
func PostCode(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldPostCode, v))
}

// Pref applies equality check predicate on the "pref" field. It's identical to PrefEQ.
func Pref(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldPref, v))
}

// City applies equality check predicate on the "city" field. It's identical to CityEQ.
func City(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldCity, v))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldAddress, v))
}

// Building applies equality check predicate on the "building" field. It's identical to BuildingEQ.
func Building(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldBuilding, v))
}

// Tel applies equality check predicate on the "tel" field. It's identical to TelEQ.
func Tel(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldTel, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldEmail, v))
}

// AccessToken applies equality check predicate on the "access_token" field. It's identical to AccessTokenEQ.
func AccessToken(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldAccessToken, v))
}

// PrivateKey applies equality check predicate on the "private_key" field. It's identical to PrivateKeyEQ.
func PrivateKey(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldPrivateKey, v))
}

// PublicKey applies equality check predicate on the "public_key" field. It's identical to PublicKeyEQ.
func PublicKey(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldPublicKey, v))
}

// Fingerprint applies equality check predicate on the "fingerprint" field. It's identical to FingerprintEQ.
func Fingerprint(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldFingerprint, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v int) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldStatus, v))
}

// StartAt applies equality check predicate on the "start_at" field. It's identical to StartAtEQ.
func StartAt(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldStartAt, v))
}

// StopAt applies equality check predicate on the "stop_at" field. It's identical to StopAtEQ.
func StopAt(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldStopAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uint) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v uint) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldUpdatedBy, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedBy applies equality check predicate on the "deleted_by" field. It's identical to DeletedByEQ.
func DeletedBy(v uint) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldDeletedBy, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldVersion, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.AppClient {
	return predicate.AppClient(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.AppClient {
	return predicate.AppClient(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldContainsFold(FieldName, v))
}

// IdentifierEQ applies the EQ predicate on the "identifier" field.
func IdentifierEQ(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldIdentifier, v))
}

// IdentifierNEQ applies the NEQ predicate on the "identifier" field.
func IdentifierNEQ(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldNEQ(FieldIdentifier, v))
}

// IdentifierIn applies the In predicate on the "identifier" field.
func IdentifierIn(vs ...string) predicate.AppClient {
	return predicate.AppClient(sql.FieldIn(FieldIdentifier, vs...))
}

// IdentifierNotIn applies the NotIn predicate on the "identifier" field.
func IdentifierNotIn(vs ...string) predicate.AppClient {
	return predicate.AppClient(sql.FieldNotIn(FieldIdentifier, vs...))
}

// IdentifierGT applies the GT predicate on the "identifier" field.
func IdentifierGT(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldGT(FieldIdentifier, v))
}

// IdentifierGTE applies the GTE predicate on the "identifier" field.
func IdentifierGTE(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldGTE(FieldIdentifier, v))
}

// IdentifierLT applies the LT predicate on the "identifier" field.
func IdentifierLT(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldLT(FieldIdentifier, v))
}

// IdentifierLTE applies the LTE predicate on the "identifier" field.
func IdentifierLTE(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldLTE(FieldIdentifier, v))
}

// IdentifierContains applies the Contains predicate on the "identifier" field.
func IdentifierContains(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldContains(FieldIdentifier, v))
}

// IdentifierHasPrefix applies the HasPrefix predicate on the "identifier" field.
func IdentifierHasPrefix(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldHasPrefix(FieldIdentifier, v))
}

// IdentifierHasSuffix applies the HasSuffix predicate on the "identifier" field.
func IdentifierHasSuffix(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldHasSuffix(FieldIdentifier, v))
}

// IdentifierEqualFold applies the EqualFold predicate on the "identifier" field.
func IdentifierEqualFold(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEqualFold(FieldIdentifier, v))
}

// IdentifierContainsFold applies the ContainsFold predicate on the "identifier" field.
func IdentifierContainsFold(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldContainsFold(FieldIdentifier, v))
}

// PostCodeEQ applies the EQ predicate on the "post_code" field.
func PostCodeEQ(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldPostCode, v))
}

// PostCodeNEQ applies the NEQ predicate on the "post_code" field.
func PostCodeNEQ(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldNEQ(FieldPostCode, v))
}

// PostCodeIn applies the In predicate on the "post_code" field.
func PostCodeIn(vs ...string) predicate.AppClient {
	return predicate.AppClient(sql.FieldIn(FieldPostCode, vs...))
}

// PostCodeNotIn applies the NotIn predicate on the "post_code" field.
func PostCodeNotIn(vs ...string) predicate.AppClient {
	return predicate.AppClient(sql.FieldNotIn(FieldPostCode, vs...))
}

// PostCodeGT applies the GT predicate on the "post_code" field.
func PostCodeGT(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldGT(FieldPostCode, v))
}

// PostCodeGTE applies the GTE predicate on the "post_code" field.
func PostCodeGTE(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldGTE(FieldPostCode, v))
}

// PostCodeLT applies the LT predicate on the "post_code" field.
func PostCodeLT(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldLT(FieldPostCode, v))
}

// PostCodeLTE applies the LTE predicate on the "post_code" field.
func PostCodeLTE(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldLTE(FieldPostCode, v))
}

// PostCodeContains applies the Contains predicate on the "post_code" field.
func PostCodeContains(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldContains(FieldPostCode, v))
}

// PostCodeHasPrefix applies the HasPrefix predicate on the "post_code" field.
func PostCodeHasPrefix(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldHasPrefix(FieldPostCode, v))
}

// PostCodeHasSuffix applies the HasSuffix predicate on the "post_code" field.
func PostCodeHasSuffix(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldHasSuffix(FieldPostCode, v))
}

// PostCodeIsNil applies the IsNil predicate on the "post_code" field.
func PostCodeIsNil() predicate.AppClient {
	return predicate.AppClient(sql.FieldIsNull(FieldPostCode))
}

// PostCodeNotNil applies the NotNil predicate on the "post_code" field.
func PostCodeNotNil() predicate.AppClient {
	return predicate.AppClient(sql.FieldNotNull(FieldPostCode))
}

// PostCodeEqualFold applies the EqualFold predicate on the "post_code" field.
func PostCodeEqualFold(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEqualFold(FieldPostCode, v))
}

// PostCodeContainsFold applies the ContainsFold predicate on the "post_code" field.
func PostCodeContainsFold(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldContainsFold(FieldPostCode, v))
}

// PrefEQ applies the EQ predicate on the "pref" field.
func PrefEQ(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldPref, v))
}

// PrefNEQ applies the NEQ predicate on the "pref" field.
func PrefNEQ(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldNEQ(FieldPref, v))
}

// PrefIn applies the In predicate on the "pref" field.
func PrefIn(vs ...string) predicate.AppClient {
	return predicate.AppClient(sql.FieldIn(FieldPref, vs...))
}

// PrefNotIn applies the NotIn predicate on the "pref" field.
func PrefNotIn(vs ...string) predicate.AppClient {
	return predicate.AppClient(sql.FieldNotIn(FieldPref, vs...))
}

// PrefGT applies the GT predicate on the "pref" field.
func PrefGT(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldGT(FieldPref, v))
}

// PrefGTE applies the GTE predicate on the "pref" field.
func PrefGTE(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldGTE(FieldPref, v))
}

// PrefLT applies the LT predicate on the "pref" field.
func PrefLT(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldLT(FieldPref, v))
}

// PrefLTE applies the LTE predicate on the "pref" field.
func PrefLTE(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldLTE(FieldPref, v))
}

// PrefContains applies the Contains predicate on the "pref" field.
func PrefContains(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldContains(FieldPref, v))
}

// PrefHasPrefix applies the HasPrefix predicate on the "pref" field.
func PrefHasPrefix(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldHasPrefix(FieldPref, v))
}

// PrefHasSuffix applies the HasSuffix predicate on the "pref" field.
func PrefHasSuffix(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldHasSuffix(FieldPref, v))
}

// PrefIsNil applies the IsNil predicate on the "pref" field.
func PrefIsNil() predicate.AppClient {
	return predicate.AppClient(sql.FieldIsNull(FieldPref))
}

// PrefNotNil applies the NotNil predicate on the "pref" field.
func PrefNotNil() predicate.AppClient {
	return predicate.AppClient(sql.FieldNotNull(FieldPref))
}

// PrefEqualFold applies the EqualFold predicate on the "pref" field.
func PrefEqualFold(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEqualFold(FieldPref, v))
}

// PrefContainsFold applies the ContainsFold predicate on the "pref" field.
func PrefContainsFold(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldContainsFold(FieldPref, v))
}

// CityEQ applies the EQ predicate on the "city" field.
func CityEQ(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldCity, v))
}

// CityNEQ applies the NEQ predicate on the "city" field.
func CityNEQ(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldNEQ(FieldCity, v))
}

// CityIn applies the In predicate on the "city" field.
func CityIn(vs ...string) predicate.AppClient {
	return predicate.AppClient(sql.FieldIn(FieldCity, vs...))
}

// CityNotIn applies the NotIn predicate on the "city" field.
func CityNotIn(vs ...string) predicate.AppClient {
	return predicate.AppClient(sql.FieldNotIn(FieldCity, vs...))
}

// CityGT applies the GT predicate on the "city" field.
func CityGT(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldGT(FieldCity, v))
}

// CityGTE applies the GTE predicate on the "city" field.
func CityGTE(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldGTE(FieldCity, v))
}

// CityLT applies the LT predicate on the "city" field.
func CityLT(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldLT(FieldCity, v))
}

// CityLTE applies the LTE predicate on the "city" field.
func CityLTE(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldLTE(FieldCity, v))
}

// CityContains applies the Contains predicate on the "city" field.
func CityContains(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldContains(FieldCity, v))
}

// CityHasPrefix applies the HasPrefix predicate on the "city" field.
func CityHasPrefix(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldHasPrefix(FieldCity, v))
}

// CityHasSuffix applies the HasSuffix predicate on the "city" field.
func CityHasSuffix(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldHasSuffix(FieldCity, v))
}

// CityIsNil applies the IsNil predicate on the "city" field.
func CityIsNil() predicate.AppClient {
	return predicate.AppClient(sql.FieldIsNull(FieldCity))
}

// CityNotNil applies the NotNil predicate on the "city" field.
func CityNotNil() predicate.AppClient {
	return predicate.AppClient(sql.FieldNotNull(FieldCity))
}

// CityEqualFold applies the EqualFold predicate on the "city" field.
func CityEqualFold(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEqualFold(FieldCity, v))
}

// CityContainsFold applies the ContainsFold predicate on the "city" field.
func CityContainsFold(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldContainsFold(FieldCity, v))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.AppClient {
	return predicate.AppClient(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.AppClient {
	return predicate.AppClient(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressIsNil applies the IsNil predicate on the "address" field.
func AddressIsNil() predicate.AppClient {
	return predicate.AppClient(sql.FieldIsNull(FieldAddress))
}

// AddressNotNil applies the NotNil predicate on the "address" field.
func AddressNotNil() predicate.AppClient {
	return predicate.AppClient(sql.FieldNotNull(FieldAddress))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldContainsFold(FieldAddress, v))
}

// BuildingEQ applies the EQ predicate on the "building" field.
func BuildingEQ(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldBuilding, v))
}

// BuildingNEQ applies the NEQ predicate on the "building" field.
func BuildingNEQ(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldNEQ(FieldBuilding, v))
}

// BuildingIn applies the In predicate on the "building" field.
func BuildingIn(vs ...string) predicate.AppClient {
	return predicate.AppClient(sql.FieldIn(FieldBuilding, vs...))
}

// BuildingNotIn applies the NotIn predicate on the "building" field.
func BuildingNotIn(vs ...string) predicate.AppClient {
	return predicate.AppClient(sql.FieldNotIn(FieldBuilding, vs...))
}

// BuildingGT applies the GT predicate on the "building" field.
func BuildingGT(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldGT(FieldBuilding, v))
}

// BuildingGTE applies the GTE predicate on the "building" field.
func BuildingGTE(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldGTE(FieldBuilding, v))
}

// BuildingLT applies the LT predicate on the "building" field.
func BuildingLT(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldLT(FieldBuilding, v))
}

// BuildingLTE applies the LTE predicate on the "building" field.
func BuildingLTE(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldLTE(FieldBuilding, v))
}

// BuildingContains applies the Contains predicate on the "building" field.
func BuildingContains(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldContains(FieldBuilding, v))
}

// BuildingHasPrefix applies the HasPrefix predicate on the "building" field.
func BuildingHasPrefix(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldHasPrefix(FieldBuilding, v))
}

// BuildingHasSuffix applies the HasSuffix predicate on the "building" field.
func BuildingHasSuffix(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldHasSuffix(FieldBuilding, v))
}

// BuildingIsNil applies the IsNil predicate on the "building" field.
func BuildingIsNil() predicate.AppClient {
	return predicate.AppClient(sql.FieldIsNull(FieldBuilding))
}

// BuildingNotNil applies the NotNil predicate on the "building" field.
func BuildingNotNil() predicate.AppClient {
	return predicate.AppClient(sql.FieldNotNull(FieldBuilding))
}

// BuildingEqualFold applies the EqualFold predicate on the "building" field.
func BuildingEqualFold(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEqualFold(FieldBuilding, v))
}

// BuildingContainsFold applies the ContainsFold predicate on the "building" field.
func BuildingContainsFold(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldContainsFold(FieldBuilding, v))
}

// TelEQ applies the EQ predicate on the "tel" field.
func TelEQ(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldTel, v))
}

// TelNEQ applies the NEQ predicate on the "tel" field.
func TelNEQ(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldNEQ(FieldTel, v))
}

// TelIn applies the In predicate on the "tel" field.
func TelIn(vs ...string) predicate.AppClient {
	return predicate.AppClient(sql.FieldIn(FieldTel, vs...))
}

// TelNotIn applies the NotIn predicate on the "tel" field.
func TelNotIn(vs ...string) predicate.AppClient {
	return predicate.AppClient(sql.FieldNotIn(FieldTel, vs...))
}

// TelGT applies the GT predicate on the "tel" field.
func TelGT(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldGT(FieldTel, v))
}

// TelGTE applies the GTE predicate on the "tel" field.
func TelGTE(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldGTE(FieldTel, v))
}

// TelLT applies the LT predicate on the "tel" field.
func TelLT(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldLT(FieldTel, v))
}

// TelLTE applies the LTE predicate on the "tel" field.
func TelLTE(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldLTE(FieldTel, v))
}

// TelContains applies the Contains predicate on the "tel" field.
func TelContains(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldContains(FieldTel, v))
}

// TelHasPrefix applies the HasPrefix predicate on the "tel" field.
func TelHasPrefix(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldHasPrefix(FieldTel, v))
}

// TelHasSuffix applies the HasSuffix predicate on the "tel" field.
func TelHasSuffix(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldHasSuffix(FieldTel, v))
}

// TelIsNil applies the IsNil predicate on the "tel" field.
func TelIsNil() predicate.AppClient {
	return predicate.AppClient(sql.FieldIsNull(FieldTel))
}

// TelNotNil applies the NotNil predicate on the "tel" field.
func TelNotNil() predicate.AppClient {
	return predicate.AppClient(sql.FieldNotNull(FieldTel))
}

// TelEqualFold applies the EqualFold predicate on the "tel" field.
func TelEqualFold(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEqualFold(FieldTel, v))
}

// TelContainsFold applies the ContainsFold predicate on the "tel" field.
func TelContainsFold(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldContainsFold(FieldTel, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.AppClient {
	return predicate.AppClient(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.AppClient {
	return predicate.AppClient(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailIsNil applies the IsNil predicate on the "email" field.
func EmailIsNil() predicate.AppClient {
	return predicate.AppClient(sql.FieldIsNull(FieldEmail))
}

// EmailNotNil applies the NotNil predicate on the "email" field.
func EmailNotNil() predicate.AppClient {
	return predicate.AppClient(sql.FieldNotNull(FieldEmail))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldContainsFold(FieldEmail, v))
}

// AccessTokenEQ applies the EQ predicate on the "access_token" field.
func AccessTokenEQ(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldAccessToken, v))
}

// AccessTokenNEQ applies the NEQ predicate on the "access_token" field.
func AccessTokenNEQ(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldNEQ(FieldAccessToken, v))
}

// AccessTokenIn applies the In predicate on the "access_token" field.
func AccessTokenIn(vs ...string) predicate.AppClient {
	return predicate.AppClient(sql.FieldIn(FieldAccessToken, vs...))
}

// AccessTokenNotIn applies the NotIn predicate on the "access_token" field.
func AccessTokenNotIn(vs ...string) predicate.AppClient {
	return predicate.AppClient(sql.FieldNotIn(FieldAccessToken, vs...))
}

// AccessTokenGT applies the GT predicate on the "access_token" field.
func AccessTokenGT(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldGT(FieldAccessToken, v))
}

// AccessTokenGTE applies the GTE predicate on the "access_token" field.
func AccessTokenGTE(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldGTE(FieldAccessToken, v))
}

// AccessTokenLT applies the LT predicate on the "access_token" field.
func AccessTokenLT(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldLT(FieldAccessToken, v))
}

// AccessTokenLTE applies the LTE predicate on the "access_token" field.
func AccessTokenLTE(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldLTE(FieldAccessToken, v))
}

// AccessTokenContains applies the Contains predicate on the "access_token" field.
func AccessTokenContains(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldContains(FieldAccessToken, v))
}

// AccessTokenHasPrefix applies the HasPrefix predicate on the "access_token" field.
func AccessTokenHasPrefix(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldHasPrefix(FieldAccessToken, v))
}

// AccessTokenHasSuffix applies the HasSuffix predicate on the "access_token" field.
func AccessTokenHasSuffix(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldHasSuffix(FieldAccessToken, v))
}

// AccessTokenEqualFold applies the EqualFold predicate on the "access_token" field.
func AccessTokenEqualFold(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEqualFold(FieldAccessToken, v))
}

// AccessTokenContainsFold applies the ContainsFold predicate on the "access_token" field.
func AccessTokenContainsFold(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldContainsFold(FieldAccessToken, v))
}

// PrivateKeyEQ applies the EQ predicate on the "private_key" field.
func PrivateKeyEQ(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldPrivateKey, v))
}

// PrivateKeyNEQ applies the NEQ predicate on the "private_key" field.
func PrivateKeyNEQ(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldNEQ(FieldPrivateKey, v))
}

// PrivateKeyIn applies the In predicate on the "private_key" field.
func PrivateKeyIn(vs ...string) predicate.AppClient {
	return predicate.AppClient(sql.FieldIn(FieldPrivateKey, vs...))
}

// PrivateKeyNotIn applies the NotIn predicate on the "private_key" field.
func PrivateKeyNotIn(vs ...string) predicate.AppClient {
	return predicate.AppClient(sql.FieldNotIn(FieldPrivateKey, vs...))
}

// PrivateKeyGT applies the GT predicate on the "private_key" field.
func PrivateKeyGT(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldGT(FieldPrivateKey, v))
}

// PrivateKeyGTE applies the GTE predicate on the "private_key" field.
func PrivateKeyGTE(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldGTE(FieldPrivateKey, v))
}

// PrivateKeyLT applies the LT predicate on the "private_key" field.
func PrivateKeyLT(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldLT(FieldPrivateKey, v))
}

// PrivateKeyLTE applies the LTE predicate on the "private_key" field.
func PrivateKeyLTE(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldLTE(FieldPrivateKey, v))
}

// PrivateKeyContains applies the Contains predicate on the "private_key" field.
func PrivateKeyContains(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldContains(FieldPrivateKey, v))
}

// PrivateKeyHasPrefix applies the HasPrefix predicate on the "private_key" field.
func PrivateKeyHasPrefix(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldHasPrefix(FieldPrivateKey, v))
}

// PrivateKeyHasSuffix applies the HasSuffix predicate on the "private_key" field.
func PrivateKeyHasSuffix(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldHasSuffix(FieldPrivateKey, v))
}

// PrivateKeyEqualFold applies the EqualFold predicate on the "private_key" field.
func PrivateKeyEqualFold(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEqualFold(FieldPrivateKey, v))
}

// PrivateKeyContainsFold applies the ContainsFold predicate on the "private_key" field.
func PrivateKeyContainsFold(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldContainsFold(FieldPrivateKey, v))
}

// PublicKeyEQ applies the EQ predicate on the "public_key" field.
func PublicKeyEQ(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldPublicKey, v))
}

// PublicKeyNEQ applies the NEQ predicate on the "public_key" field.
func PublicKeyNEQ(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldNEQ(FieldPublicKey, v))
}

// PublicKeyIn applies the In predicate on the "public_key" field.
func PublicKeyIn(vs ...string) predicate.AppClient {
	return predicate.AppClient(sql.FieldIn(FieldPublicKey, vs...))
}

// PublicKeyNotIn applies the NotIn predicate on the "public_key" field.
func PublicKeyNotIn(vs ...string) predicate.AppClient {
	return predicate.AppClient(sql.FieldNotIn(FieldPublicKey, vs...))
}

// PublicKeyGT applies the GT predicate on the "public_key" field.
func PublicKeyGT(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldGT(FieldPublicKey, v))
}

// PublicKeyGTE applies the GTE predicate on the "public_key" field.
func PublicKeyGTE(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldGTE(FieldPublicKey, v))
}

// PublicKeyLT applies the LT predicate on the "public_key" field.
func PublicKeyLT(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldLT(FieldPublicKey, v))
}

// PublicKeyLTE applies the LTE predicate on the "public_key" field.
func PublicKeyLTE(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldLTE(FieldPublicKey, v))
}

// PublicKeyContains applies the Contains predicate on the "public_key" field.
func PublicKeyContains(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldContains(FieldPublicKey, v))
}

// PublicKeyHasPrefix applies the HasPrefix predicate on the "public_key" field.
func PublicKeyHasPrefix(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldHasPrefix(FieldPublicKey, v))
}

// PublicKeyHasSuffix applies the HasSuffix predicate on the "public_key" field.
func PublicKeyHasSuffix(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldHasSuffix(FieldPublicKey, v))
}

// PublicKeyEqualFold applies the EqualFold predicate on the "public_key" field.
func PublicKeyEqualFold(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEqualFold(FieldPublicKey, v))
}

// PublicKeyContainsFold applies the ContainsFold predicate on the "public_key" field.
func PublicKeyContainsFold(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldContainsFold(FieldPublicKey, v))
}

// FingerprintEQ applies the EQ predicate on the "fingerprint" field.
func FingerprintEQ(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldFingerprint, v))
}

// FingerprintNEQ applies the NEQ predicate on the "fingerprint" field.
func FingerprintNEQ(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldNEQ(FieldFingerprint, v))
}

// FingerprintIn applies the In predicate on the "fingerprint" field.
func FingerprintIn(vs ...string) predicate.AppClient {
	return predicate.AppClient(sql.FieldIn(FieldFingerprint, vs...))
}

// FingerprintNotIn applies the NotIn predicate on the "fingerprint" field.
func FingerprintNotIn(vs ...string) predicate.AppClient {
	return predicate.AppClient(sql.FieldNotIn(FieldFingerprint, vs...))
}

// FingerprintGT applies the GT predicate on the "fingerprint" field.
func FingerprintGT(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldGT(FieldFingerprint, v))
}

// FingerprintGTE applies the GTE predicate on the "fingerprint" field.
func FingerprintGTE(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldGTE(FieldFingerprint, v))
}

// FingerprintLT applies the LT predicate on the "fingerprint" field.
func FingerprintLT(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldLT(FieldFingerprint, v))
}

// FingerprintLTE applies the LTE predicate on the "fingerprint" field.
func FingerprintLTE(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldLTE(FieldFingerprint, v))
}

// FingerprintContains applies the Contains predicate on the "fingerprint" field.
func FingerprintContains(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldContains(FieldFingerprint, v))
}

// FingerprintHasPrefix applies the HasPrefix predicate on the "fingerprint" field.
func FingerprintHasPrefix(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldHasPrefix(FieldFingerprint, v))
}

// FingerprintHasSuffix applies the HasSuffix predicate on the "fingerprint" field.
func FingerprintHasSuffix(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldHasSuffix(FieldFingerprint, v))
}

// FingerprintEqualFold applies the EqualFold predicate on the "fingerprint" field.
func FingerprintEqualFold(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldEqualFold(FieldFingerprint, v))
}

// FingerprintContainsFold applies the ContainsFold predicate on the "fingerprint" field.
func FingerprintContainsFold(v string) predicate.AppClient {
	return predicate.AppClient(sql.FieldContainsFold(FieldFingerprint, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v int) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v int) predicate.AppClient {
	return predicate.AppClient(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...int) predicate.AppClient {
	return predicate.AppClient(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...int) predicate.AppClient {
	return predicate.AppClient(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v int) predicate.AppClient {
	return predicate.AppClient(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v int) predicate.AppClient {
	return predicate.AppClient(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v int) predicate.AppClient {
	return predicate.AppClient(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v int) predicate.AppClient {
	return predicate.AppClient(sql.FieldLTE(FieldStatus, v))
}

// StartAtEQ applies the EQ predicate on the "start_at" field.
func StartAtEQ(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldStartAt, v))
}

// StartAtNEQ applies the NEQ predicate on the "start_at" field.
func StartAtNEQ(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldNEQ(FieldStartAt, v))
}

// StartAtIn applies the In predicate on the "start_at" field.
func StartAtIn(vs ...time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldIn(FieldStartAt, vs...))
}

// StartAtNotIn applies the NotIn predicate on the "start_at" field.
func StartAtNotIn(vs ...time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldNotIn(FieldStartAt, vs...))
}

// StartAtGT applies the GT predicate on the "start_at" field.
func StartAtGT(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldGT(FieldStartAt, v))
}

// StartAtGTE applies the GTE predicate on the "start_at" field.
func StartAtGTE(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldGTE(FieldStartAt, v))
}

// StartAtLT applies the LT predicate on the "start_at" field.
func StartAtLT(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldLT(FieldStartAt, v))
}

// StartAtLTE applies the LTE predicate on the "start_at" field.
func StartAtLTE(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldLTE(FieldStartAt, v))
}

// StartAtIsNil applies the IsNil predicate on the "start_at" field.
func StartAtIsNil() predicate.AppClient {
	return predicate.AppClient(sql.FieldIsNull(FieldStartAt))
}

// StartAtNotNil applies the NotNil predicate on the "start_at" field.
func StartAtNotNil() predicate.AppClient {
	return predicate.AppClient(sql.FieldNotNull(FieldStartAt))
}

// StopAtEQ applies the EQ predicate on the "stop_at" field.
func StopAtEQ(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldStopAt, v))
}

// StopAtNEQ applies the NEQ predicate on the "stop_at" field.
func StopAtNEQ(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldNEQ(FieldStopAt, v))
}

// StopAtIn applies the In predicate on the "stop_at" field.
func StopAtIn(vs ...time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldIn(FieldStopAt, vs...))
}

// StopAtNotIn applies the NotIn predicate on the "stop_at" field.
func StopAtNotIn(vs ...time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldNotIn(FieldStopAt, vs...))
}

// StopAtGT applies the GT predicate on the "stop_at" field.
func StopAtGT(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldGT(FieldStopAt, v))
}

// StopAtGTE applies the GTE predicate on the "stop_at" field.
func StopAtGTE(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldGTE(FieldStopAt, v))
}

// StopAtLT applies the LT predicate on the "stop_at" field.
func StopAtLT(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldLT(FieldStopAt, v))
}

// StopAtLTE applies the LTE predicate on the "stop_at" field.
func StopAtLTE(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldLTE(FieldStopAt, v))
}

// StopAtIsNil applies the IsNil predicate on the "stop_at" field.
func StopAtIsNil() predicate.AppClient {
	return predicate.AppClient(sql.FieldIsNull(FieldStopAt))
}

// StopAtNotNil applies the NotNil predicate on the "stop_at" field.
func StopAtNotNil() predicate.AppClient {
	return predicate.AppClient(sql.FieldNotNull(FieldStopAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uint) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uint) predicate.AppClient {
	return predicate.AppClient(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uint) predicate.AppClient {
	return predicate.AppClient(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uint) predicate.AppClient {
	return predicate.AppClient(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v uint) predicate.AppClient {
	return predicate.AppClient(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v uint) predicate.AppClient {
	return predicate.AppClient(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v uint) predicate.AppClient {
	return predicate.AppClient(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v uint) predicate.AppClient {
	return predicate.AppClient(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.AppClient {
	return predicate.AppClient(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.AppClient {
	return predicate.AppClient(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v uint) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v uint) predicate.AppClient {
	return predicate.AppClient(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...uint) predicate.AppClient {
	return predicate.AppClient(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...uint) predicate.AppClient {
	return predicate.AppClient(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v uint) predicate.AppClient {
	return predicate.AppClient(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v uint) predicate.AppClient {
	return predicate.AppClient(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v uint) predicate.AppClient {
	return predicate.AppClient(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v uint) predicate.AppClient {
	return predicate.AppClient(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.AppClient {
	return predicate.AppClient(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.AppClient {
	return predicate.AppClient(sql.FieldNotNull(FieldUpdatedBy))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.AppClient {
	return predicate.AppClient(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.AppClient {
	return predicate.AppClient(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.AppClient {
	return predicate.AppClient(sql.FieldNotNull(FieldDeletedAt))
}

// DeletedByEQ applies the EQ predicate on the "deleted_by" field.
func DeletedByEQ(v uint) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "deleted_by" field.
func DeletedByNEQ(v uint) predicate.AppClient {
	return predicate.AppClient(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "deleted_by" field.
func DeletedByIn(vs ...uint) predicate.AppClient {
	return predicate.AppClient(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "deleted_by" field.
func DeletedByNotIn(vs ...uint) predicate.AppClient {
	return predicate.AppClient(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByGT applies the GT predicate on the "deleted_by" field.
func DeletedByGT(v uint) predicate.AppClient {
	return predicate.AppClient(sql.FieldGT(FieldDeletedBy, v))
}

// DeletedByGTE applies the GTE predicate on the "deleted_by" field.
func DeletedByGTE(v uint) predicate.AppClient {
	return predicate.AppClient(sql.FieldGTE(FieldDeletedBy, v))
}

// DeletedByLT applies the LT predicate on the "deleted_by" field.
func DeletedByLT(v uint) predicate.AppClient {
	return predicate.AppClient(sql.FieldLT(FieldDeletedBy, v))
}

// DeletedByLTE applies the LTE predicate on the "deleted_by" field.
func DeletedByLTE(v uint) predicate.AppClient {
	return predicate.AppClient(sql.FieldLTE(FieldDeletedBy, v))
}

// DeletedByIsNil applies the IsNil predicate on the "deleted_by" field.
func DeletedByIsNil() predicate.AppClient {
	return predicate.AppClient(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "deleted_by" field.
func DeletedByNotNil() predicate.AppClient {
	return predicate.AppClient(sql.FieldNotNull(FieldDeletedBy))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int) predicate.AppClient {
	return predicate.AppClient(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int) predicate.AppClient {
	return predicate.AppClient(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int) predicate.AppClient {
	return predicate.AppClient(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int) predicate.AppClient {
	return predicate.AppClient(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int) predicate.AppClient {
	return predicate.AppClient(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int) predicate.AppClient {
	return predicate.AppClient(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int) predicate.AppClient {
	return predicate.AppClient(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int) predicate.AppClient {
	return predicate.AppClient(sql.FieldLTE(FieldVersion, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AppClient) predicate.AppClient {
	return predicate.AppClient(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AppClient) predicate.AppClient {
	return predicate.AppClient(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AppClient) predicate.AppClient {
	return predicate.AppClient(sql.NotPredicates(p))
}
