source "https://rubygems.org"

gem "hanami"
gem "hanami-controller"
gem "hanami-router"
gem "puma"
gem "rom"
gem "rom-sql"
gem "mysql2"
gem "redis"
gem "dotenv"
gem "dry-validation"
gem "mail"
gem "jwt"

group :test do
  gem "rspec"
  gem "rack-test"
end
